import OCL from 'openchemlib';

import { fragmentCyclicBonds } from '../fragmentCyclicBonds.js';

const { Molecule } = OCL;

describe('fragmentCyclicBonds', () => {
  it('CCCC', () => {
    const molecule = Molecule.fromSmiles('CCCC'); // butane
    const result = fragmentCyclicBonds(molecule);

    expect(result).toStrictEqual([]);
  });
  it('C1CC1', () => {
    const molecule = Molecule.fromSmiles('C1CC1'); // butane
    const result = fragmentCyclicBonds(molecule);
    expect(result).toStrictEqual([]);
  });

  it('c1ccncc1', () => {
    const molecule = Molecule.fromSmiles('c1ccncc1'); // benzene
    const result = fragmentCyclicBonds(molecule);

    expect(result).toStrictEqual([]);
  });

  it('CCC13CCCC2CCCC(CCC1)C23', () => {
    const molecule = Molecule.fromSmiles('C1CC2CCCC3CCCC(C1)C23'); //3 cyclohexane connected
    const result = fragmentCyclicBonds(molecule);
    expect(result).toStrictEqual([
      {
        hose: {
          bond1: {
            atoms: [0, 1],
            from: 0,
            to: 1,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [10, 11],
            from: 10,
            to: 11,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'A',
      },
      {
        hose: {
          bond1: {
            atoms: [0, 1],
            from: 0,
            to: 1,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [10, 11],
            from: 10,
            to: 11,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [1],
        mf: 'C11H19',
        idCode: 'dcl@`@V\\bTTRbOBnuUUUP@@',
        mfInfo: {
          mass: 151.2689691911475,
          monoisotopicMass: 151.14867561237,
          charge: 0,
          mf: 'C11H19',
          atoms: { C: 11, H: 19 },
          unsaturation: 2.5,
        },
        fragmentType: 'cyclic',
        code: 'B',
      },
      {
        hose: {
          bond1: {
            atoms: [1, 2],
            from: 1,
            to: 2,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [10, 11],
            from: 10,
            to: 11,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C3H7',
        idCode: 'gC`H@liMT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'C',
      },
      {
        hose: {
          bond1: {
            atoms: [1, 2],
            from: 1,
            to: 2,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [10, 11],
            from: 10,
            to: 11,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [2],
        mf: 'C10H17',
        idCode: 'dmL@`@V\\bbbTQ[iVjjjh@@',
        mfInfo: {
          mass: 137.2423517863007,
          monoisotopicMass: 137.13302554791,
          charge: 0,
          mf: 'C10H17',
          atoms: { C: 10, H: 17 },
          unsaturation: 2.5,
        },
        fragmentType: 'cyclic',
        code: 'D',
      },
      {
        hose: {
          bond1: {
            atoms: [1, 2],
            from: 1,
            to: 2,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [0, 11],
            from: 0,
            to: 11,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'E',
      },
      {
        hose: {
          bond1: {
            atoms: [1, 2],
            from: 1,
            to: 2,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [0, 11],
            from: 0,
            to: 11,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [2],
        mf: 'C11H19',
        idCode: 'dcl@`@V\\bbbTTK]NuUUUP@@',
        mfInfo: {
          mass: 151.2689691911475,
          monoisotopicMass: 151.14867561237,
          charge: 0,
          mf: 'C11H19',
          atoms: { C: 11, H: 19 },
          unsaturation: 2.5,
        },
        fragmentType: 'cyclic',
        code: 'F',
      },
      {
        hose: {
          bond1: {
            atoms: [6, 7],
            from: 6,
            to: 7,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [8, 9],
            from: 8,
            to: 9,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C11H19',
        idCode: 'dcl@`@VTfUe^fWZjjjh@@',
        mfInfo: {
          mass: 151.2689691911475,
          monoisotopicMass: 151.14867561237,
          charge: 0,
          mf: 'C11H19',
          atoms: { C: 11, H: 19 },
          unsaturation: 2.5,
        },
        fragmentType: 'cyclic',
        code: 'G',
      },
      {
        hose: {
          bond1: {
            atoms: [6, 7],
            from: 6,
            to: 7,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [8, 9],
            from: 8,
            to: 9,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [7],
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'H',
      },
      {
        hose: {
          bond1: {
            atoms: [6, 7],
            from: 6,
            to: 7,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [9, 10],
            from: 9,
            to: 10,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C10H17',
        idCode: 'dmL@`@VTfUmZZUjjjj@@',
        mfInfo: {
          mass: 137.2423517863007,
          monoisotopicMass: 137.13302554791,
          charge: 0,
          mf: 'C10H17',
          atoms: { C: 10, H: 17 },
          unsaturation: 2.5,
        },
        fragmentType: 'cyclic',
        code: 'I',
      },
      {
        hose: {
          bond1: {
            atoms: [6, 7],
            from: 6,
            to: 7,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [9, 10],
            from: 9,
            to: 10,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [7],
        mf: 'C3H7',
        idCode: 'gC`H@liKT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'J',
      },
      {
        hose: {
          bond1: {
            atoms: [7, 8],
            from: 7,
            to: 8,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [9, 10],
            from: 9,
            to: 10,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C11H19',
        idCode: 'dcl@`@VTfUmZfeZjjjh@@',
        mfInfo: {
          mass: 151.2689691911475,
          monoisotopicMass: 151.14867561237,
          charge: 0,
          mf: 'C11H19',
          atoms: { C: 11, H: 19 },
          unsaturation: 2.5,
        },
        fragmentType: 'cyclic',
        code: 'K',
      },
      {
        hose: {
          bond1: {
            atoms: [7, 8],
            from: 7,
            to: 8,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [9, 10],
            from: 9,
            to: 10,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [8],
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'L',
      },
      {
        hose: {
          bond1: {
            atoms: [2, 3],
            from: 2,
            to: 3,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [4, 5],
            from: 4,
            to: 5,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C11H19',
        idCode: 'dcl@`@VTfUmZfeZjjjh@@',
        mfInfo: {
          mass: 151.2689691911475,
          monoisotopicMass: 151.14867561237,
          charge: 0,
          mf: 'C11H19',
          atoms: { C: 11, H: 19 },
          unsaturation: 2.5,
        },
        fragmentType: 'cyclic',
        code: 'M',
      },
      {
        hose: {
          bond1: {
            atoms: [2, 3],
            from: 2,
            to: 3,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [4, 5],
            from: 4,
            to: 5,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [3],
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'N',
      },
      {
        hose: {
          bond1: {
            atoms: [2, 3],
            from: 2,
            to: 3,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [5, 6],
            from: 5,
            to: 6,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C10H17',
        idCode: 'dmL@`@VTfUmZZUjjjj@@',
        mfInfo: {
          mass: 137.2423517863007,
          monoisotopicMass: 137.13302554791,
          charge: 0,
          mf: 'C10H17',
          atoms: { C: 10, H: 17 },
          unsaturation: 2.5,
        },
        fragmentType: 'cyclic',
        code: 'O',
      },
      {
        hose: {
          bond1: {
            atoms: [2, 3],
            from: 2,
            to: 3,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [5, 6],
            from: 5,
            to: 6,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [3],
        mf: 'C3H7',
        idCode: 'gC`H@liKT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'P',
      },
      {
        hose: {
          bond1: {
            atoms: [3, 4],
            from: 3,
            to: 4,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [5, 6],
            from: 5,
            to: 6,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C11H19',
        idCode: 'dcl@`@VTfUe^fWZjjjh@@',
        mfInfo: {
          mass: 151.2689691911475,
          monoisotopicMass: 151.14867561237,
          charge: 0,
          mf: 'C11H19',
          atoms: { C: 11, H: 19 },
          unsaturation: 2.5,
        },
        fragmentType: 'cyclic',
        code: 'Q',
      },
      {
        hose: {
          bond1: {
            atoms: [3, 4],
            from: 3,
            to: 4,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [5, 6],
            from: 5,
            to: 6,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [4],
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'R',
      },
    ]);
  });

  it('C2CCC1CCCCC1C2', () => {
    const molecule = Molecule.fromSmiles('C2CCC1CCCCC1C2'); //2 cyclohexane
    const result = fragmentCyclicBonds(molecule);
    expect(result).toStrictEqual([
      {
        hose: {
          bond1: {
            atoms: [3, 4],
            from: 3,
            to: 4,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [5, 6],
            from: 5,
            to: 6,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gFp@DiTvjhCaB`eAxcIbsY~bPNEUGBj@' },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C8H15',
        idCode: 'did@`@V\\bbRaijjj`@',
        mfInfo: {
          mass: 111.20499848471864,
          monoisotopicMass: 111.11737548345,
          charge: 0,
          mf: 'C8H15',
          atoms: { C: 8, H: 15 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
        code: 'A',
      },
      {
        hose: {
          bond1: {
            atoms: [3, 4],
            from: 3,
            to: 4,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [5, 6],
            from: 5,
            to: 6,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gFp@DiTvjhCaB`eAxcIbsY~bPNEUGBj@' },
            ],
            length: 1,
          },
        },
        atomMap: [4],
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'B',
      },
      {
        hose: {
          bond1: {
            atoms: [3, 4],
            from: 3,
            to: 4,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [6, 7],
            from: 6,
            to: 7,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C7H13',
        idCode: 'daD@`@VTfUjZjj`@',
        mfInfo: {
          mass: 97.17838107987185,
          monoisotopicMass: 97.10172541899,
          charge: 0,
          mf: 'C7H13',
          atoms: { C: 7, H: 13 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
        code: 'C',
      },
      {
        hose: {
          bond1: {
            atoms: [3, 4],
            from: 3,
            to: 4,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [6, 7],
            from: 6,
            to: 7,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [4],
        mf: 'C3H7',
        idCode: 'gC`H@liKT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'D',
      },
      {
        hose: {
          bond1: {
            atoms: [3, 4],
            from: 3,
            to: 4,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [7, 8],
            from: 7,
            to: 8,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C6H11',
        idCode: 'gOpH@liLkWUU@@',
        mfInfo: {
          mass: 83.15176367502504,
          monoisotopicMass: 83.08607535453,
          charge: 0,
          mf: 'C6H11',
          atoms: { C: 6, H: 11 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
        code: 'E',
      },
      {
        hose: {
          bond1: {
            atoms: [3, 4],
            from: 3,
            to: 4,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [7, 8],
            from: 7,
            to: 8,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [4],
        mf: 'C4H9',
        idCode: 'gJPH@liJuP@',
        mfInfo: {
          mass: 57.114410373442986,
          monoisotopicMass: 57.07042529007,
          charge: 0,
          mf: 'C4H9',
          atoms: { C: 4, H: 9 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'F',
      },
      {
        hose: {
          bond1: {
            atoms: [4, 5],
            from: 4,
            to: 5,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [6, 7],
            from: 6,
            to: 7,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C8H15',
        idCode: 'did@`@VTfUnfjjj@@',
        mfInfo: {
          mass: 111.20499848471864,
          monoisotopicMass: 111.11737548345,
          charge: 0,
          mf: 'C8H15',
          atoms: { C: 8, H: 15 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
        code: 'G',
      },
      {
        hose: {
          bond1: {
            atoms: [4, 5],
            from: 4,
            to: 5,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [6, 7],
            from: 6,
            to: 7,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [5],
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'H',
      },
      {
        hose: {
          bond1: {
            atoms: [4, 5],
            from: 4,
            to: 5,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [7, 8],
            from: 7,
            to: 8,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C7H13',
        idCode: 'daD@`@VTfUzZjj`@',
        mfInfo: {
          mass: 97.17838107987185,
          monoisotopicMass: 97.10172541899,
          charge: 0,
          mf: 'C7H13',
          atoms: { C: 7, H: 13 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
        code: 'I',
      },
      {
        hose: {
          bond1: {
            atoms: [4, 5],
            from: 4,
            to: 5,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [7, 8],
            from: 7,
            to: 8,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [5],
        mf: 'C3H7',
        idCode: 'gC`H@liKT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'J',
      },
      {
        hose: {
          bond1: {
            atoms: [5, 6],
            from: 5,
            to: 6,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gFp@DiTvjhCaB`eAxcIbsY~bPNEUGBj@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [7, 8],
            from: 7,
            to: 8,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C8H15',
        idCode: 'did@`@VTfUvfjjj@@',
        mfInfo: {
          mass: 111.20499848471864,
          monoisotopicMass: 111.11737548345,
          charge: 0,
          mf: 'C8H15',
          atoms: { C: 8, H: 15 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
        code: 'K',
      },
      {
        hose: {
          bond1: {
            atoms: [5, 6],
            from: 5,
            to: 6,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gFp@DiTvjhCaB`eAxcIbsY~bPNEUGBj@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [7, 8],
            from: 7,
            to: 8,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [6],
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'L',
      },
      {
        hose: {
          bond1: {
            atoms: [0, 1],
            from: 0,
            to: 1,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gFp@DiTvjhCaB`eAxcIbsY~bPNEUGBj@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [2, 3],
            from: 2,
            to: 3,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C8H15',
        idCode: 'did@`@VTeYWajjj@@',
        mfInfo: {
          mass: 111.20499848471864,
          monoisotopicMass: 111.11737548345,
          charge: 0,
          mf: 'C8H15',
          atoms: { C: 8, H: 15 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
        code: 'M',
      },
      {
        hose: {
          bond1: {
            atoms: [0, 1],
            from: 0,
            to: 1,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gFp@DiTvjhCaB`eAxcIbsY~bPNEUGBj@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [2, 3],
            from: 2,
            to: 3,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [1],
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'N',
      },
      {
        hose: {
          bond1: {
            atoms: [0, 1],
            from: 0,
            to: 1,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gFp@DiTvjhCaB`eAxcIbsY~bPNEUGBj@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [8, 9],
            from: 8,
            to: 9,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'O',
      },
      {
        hose: {
          bond1: {
            atoms: [0, 1],
            from: 0,
            to: 1,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gFp@DiTvjhCaB`eAxcIbsY~bPNEUGBj@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [8, 9],
            from: 8,
            to: 9,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [1],
        mf: 'C8H15',
        idCode: 'did@`@VTeYWajjj@@',
        mfInfo: {
          mass: 111.20499848471864,
          monoisotopicMass: 111.11737548345,
          charge: 0,
          mf: 'C8H15',
          atoms: { C: 8, H: 15 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
        code: 'P',
      },
      {
        hose: {
          bond1: {
            atoms: [1, 2],
            from: 1,
            to: 2,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [8, 9],
            from: 8,
            to: 9,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C3H7',
        idCode: 'gC`H@liMT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'Q',
      },
      {
        hose: {
          bond1: {
            atoms: [1, 2],
            from: 1,
            to: 2,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [8, 9],
            from: 8,
            to: 9,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [2],
        mf: 'C7H13',
        idCode: 'daD@`@VTeeVzjj`@',
        mfInfo: {
          mass: 97.17838107987185,
          monoisotopicMass: 97.10172541899,
          charge: 0,
          mf: 'C7H13',
          atoms: { C: 7, H: 13 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
        code: 'R',
      },
      {
        hose: {
          bond1: {
            atoms: [1, 2],
            from: 1,
            to: 2,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [0, 9],
            from: 0,
            to: 9,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'S',
      },
      {
        hose: {
          bond1: {
            atoms: [1, 2],
            from: 1,
            to: 2,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [0, 9],
            from: 0,
            to: 9,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [2],
        mf: 'C8H15',
        idCode: 'did@`@VTefWajjj@@',
        mfInfo: {
          mass: 111.20499848471864,
          monoisotopicMass: 111.11737548345,
          charge: 0,
          mf: 'C8H15',
          atoms: { C: 8, H: 15 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
        code: 'T',
      },
      {
        hose: {
          bond1: {
            atoms: [2, 3],
            from: 2,
            to: 3,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [8, 9],
            from: 8,
            to: 9,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C4H9',
        idCode: 'gJPH@liLuP@',
        mfInfo: {
          mass: 57.114410373442986,
          monoisotopicMass: 57.07042529007,
          charge: 0,
          mf: 'C4H9',
          atoms: { C: 4, H: 9 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'U',
      },
      {
        hose: {
          bond1: {
            atoms: [2, 3],
            from: 2,
            to: 3,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [8, 9],
            from: 8,
            to: 9,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [3],
        mf: 'C6H11',
        idCode: 'gOpH@liLkWUU@@',
        mfInfo: {
          mass: 83.15176367502504,
          monoisotopicMass: 83.08607535453,
          charge: 0,
          mf: 'C6H11',
          atoms: { C: 6, H: 11 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
        code: 'V',
      },
      {
        hose: {
          bond1: {
            atoms: [2, 3],
            from: 2,
            to: 3,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [0, 9],
            from: 0,
            to: 9,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C3H7',
        idCode: 'gC`H@liKT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'W',
      },
      {
        hose: {
          bond1: {
            atoms: [2, 3],
            from: 2,
            to: 3,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [0, 9],
            from: 0,
            to: 9,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [3],
        mf: 'C7H13',
        idCode: 'daD@`@VTfYVzjj`@',
        mfInfo: {
          mass: 97.17838107987185,
          monoisotopicMass: 97.10172541899,
          charge: 0,
          mf: 'C7H13',
          atoms: { C: 7, H: 13 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
        code: 'X',
      },
    ]);

    // Bug: getRingSet do not reconise rings with less than 6 carbons and with more than 7
  });
  it('C2CCC1CCCC3CCCC4CCCC1', () => {
    const molecule = Molecule.fromSmiles('C2CCC1CCCC3CCCC4CCCC1(CC2)C34'); //4 cycles (2 hexane & 2 heptane)
    const result = fragmentCyclicBonds(molecule);
    expect(result).toStrictEqual([
      {
        hose: {
          bond1: {
            atoms: [0, 1],
            from: 0,
            to: 1,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [2, 3],
            from: 2,
            to: 3,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              { sphere: 2, oclID: 'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C17H29',
        idCode: 'fde@B@@KNQIJQQIQQGScA}Fjjjjjj`@@',
        mfInfo: {
          mass: 233.41279211211676,
          monoisotopicMass: 233.22692593467,
          charge: 0,
          mf: 'C17H29',
          atoms: { C: 17, H: 29 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
        code: 'A',
      },
      {
        hose: {
          bond1: {
            atoms: [0, 1],
            from: 0,
            to: 1,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [2, 3],
            from: 2,
            to: 3,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              { sphere: 2, oclID: 'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [1],
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'B',
      },
      {
        hose: {
          bond1: {
            atoms: [0, 1],
            from: 0,
            to: 1,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [15, 16],
            from: 15,
            to: 16,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@' },
              { sphere: 2, oclID: 'dct@@DjefVjjj`Ca@hHhOUFIFPVUgzH`NEUCaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C3H7',
        idCode: 'gC`H@liKT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'C',
      },
      {
        hose: {
          bond1: {
            atoms: [0, 1],
            from: 0,
            to: 1,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [15, 16],
            from: 15,
            to: 16,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@' },
              { sphere: 2, oclID: 'dct@@DjefVjjj`Ca@hHhOUFIFPVUgzH`NEUCaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [1],
        mf: 'C16H27',
        idCode: 'fhy@B@@KNQIQQJIIPrMiw`uUUUUUP@@',
        mfInfo: {
          mass: 219.38617470726996,
          monoisotopicMass: 219.21127587021,
          charge: 0,
          mf: 'C16H27',
          atoms: { C: 16, H: 27 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
        code: 'D',
      },
      {
        hose: {
          bond1: {
            atoms: [0, 1],
            from: 0,
            to: 1,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [16, 17],
            from: 16,
            to: 17,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'dax@@DiZZjh@xPJBJCvAdYf_hb@xUTNET' },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'E',
      },
      {
        hose: {
          bond1: {
            atoms: [0, 1],
            from: 0,
            to: 1,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [16, 17],
            from: 16,
            to: 17,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'dax@@DiZZjh@xPJBJCvAdYf_hb@xUTNET' },
            ],
            length: 1,
          },
        },
        atomMap: [1],
        mf: 'C17H29',
        idCode: 'fde@B@@KNQIQRIQYJEUc^CFjjjjjj`@@',
        mfInfo: {
          mass: 233.41279211211676,
          monoisotopicMass: 233.22692593467,
          charge: 0,
          mf: 'C17H29',
          atoms: { C: 17, H: 29 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
        code: 'F',
      },
      {
        hose: {
          bond1: {
            atoms: [1, 2],
            from: 1,
            to: 2,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [15, 16],
            from: 15,
            to: 16,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@' },
              { sphere: 2, oclID: 'dct@@DjefVjjj`Ca@hHhOUFIFPVUgzH`NEUCaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C4H9',
        idCode: 'gJPH@liLuP@',
        mfInfo: {
          mass: 57.114410373442986,
          monoisotopicMass: 57.07042529007,
          charge: 0,
          mf: 'C4H9',
          atoms: { C: 4, H: 9 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'G',
      },
      {
        hose: {
          bond1: {
            atoms: [1, 2],
            from: 1,
            to: 2,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [15, 16],
            from: 15,
            to: 16,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@' },
              { sphere: 2, oclID: 'dct@@DjefVjjj`Ca@hHhOUFIFPVUgzH`NEUCaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [2],
        mf: 'C15H25',
        idCode: 'f`i@B@@KNQJJIQIJDVeV]zjjjjjh@@',
        mfInfo: {
          mass: 205.35955730242316,
          monoisotopicMass: 205.19562580575,
          charge: 0,
          mf: 'C15H25',
          atoms: { C: 15, H: 25 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
        code: 'H',
      },
      {
        hose: {
          bond1: {
            atoms: [1, 2],
            from: 1,
            to: 2,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [16, 17],
            from: 16,
            to: 17,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'dax@@DiZZjh@xPJBJCvAdYf_hb@xUTNET' },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C3H7',
        idCode: 'gC`H@liMT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'I',
      },
      {
        hose: {
          bond1: {
            atoms: [1, 2],
            from: 1,
            to: 2,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [16, 17],
            from: 16,
            to: 17,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'dax@@DiZZjh@xPJBJCvAdYf_hb@xUTNET' },
            ],
            length: 1,
          },
        },
        atomMap: [2],
        mf: 'C16H27',
        idCode: 'fhy@B@@KNQJJQJKIPrMiw`uUUUUUP@@',
        mfInfo: {
          mass: 219.38617470726996,
          monoisotopicMass: 219.21127587021,
          charge: 0,
          mf: 'C16H27',
          atoms: { C: 16, H: 27 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
        code: 'J',
      },
      {
        hose: {
          bond1: {
            atoms: [1, 2],
            from: 1,
            to: 2,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [0, 17],
            from: 0,
            to: 17,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh' },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'K',
      },
      {
        hose: {
          bond1: {
            atoms: [1, 2],
            from: 1,
            to: 2,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [0, 17],
            from: 0,
            to: 17,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh' },
            ],
            length: 1,
          },
        },
        atomMap: [2],
        mf: 'C17H29',
        idCode: 'fde@B@@KNQJJQJIIJVUm^CFjjjjjj`@@',
        mfInfo: {
          mass: 233.41279211211676,
          monoisotopicMass: 233.22692593467,
          charge: 0,
          mf: 'C17H29',
          atoms: { C: 17, H: 29 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
        code: 'L',
      },
      {
        hose: {
          bond1: {
            atoms: [2, 3],
            from: 2,
            to: 3,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              { sphere: 2, oclID: 'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [15, 16],
            from: 15,
            to: 16,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@' },
              { sphere: 2, oclID: 'dct@@DjefVjjj`Ca@hHhOUFIFPVUgzH`NEUCaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C5H11',
        idCode: 'gGPH@liLmU@@',
        mfInfo: {
          mass: 71.1410277782898,
          monoisotopicMass: 71.08607535453,
          charge: 0,
          mf: 'C5H11',
          atoms: { C: 5, H: 11 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'M',
      },
      {
        hose: {
          bond1: {
            atoms: [2, 3],
            from: 2,
            to: 3,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              { sphere: 2, oclID: 'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [15, 16],
            from: 15,
            to: 16,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@' },
              { sphere: 2, oclID: 'dct@@DjefVjjj`Ca@hHhOUFIFPVUgzH`NEUCaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [3],
        mf: 'C14H23',
        idCode: 'foQ@B@@KNQQQJIIP|UHugUUUUUT@@',
        mfInfo: {
          mass: 191.33293989757635,
          monoisotopicMass: 191.17997574129,
          charge: 0,
          mf: 'C14H23',
          atoms: { C: 14, H: 23 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
        code: 'N',
      },
      {
        hose: {
          bond1: {
            atoms: [2, 3],
            from: 2,
            to: 3,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              { sphere: 2, oclID: 'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [16, 17],
            from: 16,
            to: 17,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'dax@@DiZZjh@xPJBJCvAdYf_hb@xUTNET' },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C4H9',
        idCode: 'gJPH@liLuP@',
        mfInfo: {
          mass: 57.114410373442986,
          monoisotopicMass: 57.07042529007,
          charge: 0,
          mf: 'C4H9',
          atoms: { C: 4, H: 9 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'O',
      },
      {
        hose: {
          bond1: {
            atoms: [2, 3],
            from: 2,
            to: 3,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              { sphere: 2, oclID: 'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [16, 17],
            from: 16,
            to: 17,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'dax@@DiZZjh@xPJBJCvAdYf_hb@xUTNET' },
            ],
            length: 1,
          },
        },
        atomMap: [3],
        mf: 'C15H25',
        idCode: 'f`i@B@@KNQQRIQYJDVeV]zjjjjjh@@',
        mfInfo: {
          mass: 205.35955730242316,
          monoisotopicMass: 205.19562580575,
          charge: 0,
          mf: 'C15H25',
          atoms: { C: 15, H: 25 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
        code: 'P',
      },
      {
        hose: {
          bond1: {
            atoms: [2, 3],
            from: 2,
            to: 3,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              { sphere: 2, oclID: 'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [0, 17],
            from: 0,
            to: 17,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh' },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C3H7',
        idCode: 'gC`H@liKT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'Q',
      },
      {
        hose: {
          bond1: {
            atoms: [2, 3],
            from: 2,
            to: 3,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              { sphere: 2, oclID: 'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [0, 17],
            from: 0,
            to: 17,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh' },
            ],
            length: 1,
          },
        },
        atomMap: [3],
        mf: 'C16H27',
        idCode: 'fhy@B@@KNQQRIQIIRbLiw`uUUUUUP@@',
        mfInfo: {
          mass: 219.38617470726996,
          monoisotopicMass: 219.21127587021,
          charge: 0,
          mf: 'C16H27',
          atoms: { C: 16, H: 27 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
        code: 'R',
      },
      {
        hose: {
          bond1: {
            atoms: [15, 16],
            from: 15,
            to: 16,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@' },
              { sphere: 2, oclID: 'dct@@DjefVjjj`Ca@hHhOUFIFPVUgzH`NEUCaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [0, 17],
            from: 0,
            to: 17,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh' },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C17H29',
        idCode: 'fde@B@@KNQIJJIQIJEUc^CFjjjjjj`@@',
        mfInfo: {
          mass: 233.41279211211676,
          monoisotopicMass: 233.22692593467,
          charge: 0,
          mf: 'C17H29',
          atoms: { C: 17, H: 29 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
        code: 'S',
      },
      {
        hose: {
          bond1: {
            atoms: [15, 16],
            from: 15,
            to: 16,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@' },
              { sphere: 2, oclID: 'dct@@DjefVjjj`Ca@hHhOUFIFPVUgzH`NEUCaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [0, 17],
            from: 0,
            to: 17,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh' },
            ],
            length: 1,
          },
        },
        atomMap: [16],
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'T',
      },
      {
        hose: {
          bond1: {
            atoms: [3, 4],
            from: 3,
            to: 4,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              { sphere: 2, oclID: 'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [5, 6],
            from: 5,
            to: 6,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`' },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C17H29',
        idCode: 'fde@B@@KNQQIISQJJEgCV}Fjjjjjj`@@',
        mfInfo: {
          mass: 233.41279211211676,
          monoisotopicMass: 233.22692593467,
          charge: 0,
          mf: 'C17H29',
          atoms: { C: 17, H: 29 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
        code: 'U',
      },
      {
        hose: {
          bond1: {
            atoms: [3, 4],
            from: 3,
            to: 4,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              { sphere: 2, oclID: 'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [5, 6],
            from: 5,
            to: 6,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`' },
            ],
            length: 1,
          },
        },
        atomMap: [4],
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'V',
      },
      {
        hose: {
          bond1: {
            atoms: [3, 4],
            from: 3,
            to: 4,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              { sphere: 2, oclID: 'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [6, 7],
            from: 6,
            to: 7,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              { sphere: 2, oclID: 'diD@@DjVVjjhB`NDB`b`}PQFIFXV_hb@xUTNET' },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C16H27',
        idCode: 'fhy@B@@KNQQIISQJHlxZw`uUUUUUP@@',
        mfInfo: {
          mass: 219.38617470726996,
          monoisotopicMass: 219.21127587021,
          charge: 0,
          mf: 'C16H27',
          atoms: { C: 16, H: 27 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
        code: 'W',
      },
      {
        hose: {
          bond1: {
            atoms: [3, 4],
            from: 3,
            to: 4,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              { sphere: 2, oclID: 'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [6, 7],
            from: 6,
            to: 7,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              { sphere: 2, oclID: 'diD@@DjVVjjhB`NDB`b`}PQFIFXV_hb@xUTNET' },
            ],
            length: 1,
          },
        },
        atomMap: [4],
        mf: 'C3H7',
        idCode: 'gC`H@liKT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'X',
      },
      {
        hose: {
          bond1: {
            atoms: [4, 5],
            from: 4,
            to: 5,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [6, 7],
            from: 6,
            to: 7,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              { sphere: 2, oclID: 'diD@@DjVVjjhB`NDB`b`}PQFIFXV_hb@xUTNET' },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C17H29',
        idCode: 'fde@B@@KNQQIIQJKQEgKNCFjjjjjj`@@',
        mfInfo: {
          mass: 233.41279211211676,
          monoisotopicMass: 233.22692593467,
          charge: 0,
          mf: 'C17H29',
          atoms: { C: 17, H: 29 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
        code: 'Y',
      },
      {
        hose: {
          bond1: {
            atoms: [4, 5],
            from: 4,
            to: 5,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [6, 7],
            from: 6,
            to: 7,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              { sphere: 2, oclID: 'diD@@DjVVjjhB`NDB`b`}PQFIFXV_hb@xUTNET' },
            ],
            length: 1,
          },
        },
        atomMap: [5],
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'Z',
      },
      {
        hose: {
          bond1: {
            atoms: [11, 12],
            from: 11,
            to: 12,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [13, 14],
            from: 13,
            to: 14,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'daD@@DiZRzjj`Ca@hHhOXFQfY~bHCaUPxUP' },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C17H29',
        idCode: 'fde@B@@KNQQIIQJYQEgKNCFjjjjjj`@@',
        mfInfo: {
          mass: 233.41279211211676,
          monoisotopicMass: 233.22692593467,
          charge: 0,
          mf: 'C17H29',
          atoms: { C: 17, H: 29 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
        code: '[',
      },
      {
        hose: {
          bond1: {
            atoms: [11, 12],
            from: 11,
            to: 12,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [13, 14],
            from: 13,
            to: 14,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'daD@@DiZRzjj`Ca@hHhOXFQfY~bHCaUPxUP' },
            ],
            length: 1,
          },
        },
        atomMap: [12],
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: '\\',
      },
      {
        hose: {
          bond1: {
            atoms: [11, 12],
            from: 11,
            to: 12,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [14, 15],
            from: 14,
            to: 15,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@' },
              {
                sphere: 2,
                oclID: 'dcL@@DjefUmjjjjPJDHCa@hHhOUFIFPVUgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C16H27',
        idCode: 'fhy@B@@KNQQIIIQJHlxZw`uUUUUUP@@',
        mfInfo: {
          mass: 219.38617470726996,
          monoisotopicMass: 219.21127587021,
          charge: 0,
          mf: 'C16H27',
          atoms: { C: 16, H: 27 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
        code: ']',
      },
      {
        hose: {
          bond1: {
            atoms: [11, 12],
            from: 11,
            to: 12,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [14, 15],
            from: 14,
            to: 15,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@' },
              {
                sphere: 2,
                oclID: 'dcL@@DjefUmjjjjPJDHCa@hHhOUFIFPVUgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [12],
        mf: 'C3H7',
        idCode: 'gC`H@liKT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: '^',
      },
      {
        hose: {
          bond1: {
            atoms: [12, 13],
            from: 12,
            to: 13,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [14, 15],
            from: 14,
            to: 15,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@' },
              {
                sphere: 2,
                oclID: 'dcL@@DjefUmjjjjPJDHCa@hHhOUFIFPVUgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C17H29',
        idCode: 'fde@B@@KNQQIIIQJJEgCV}Fjjjjjj`@@',
        mfInfo: {
          mass: 233.41279211211676,
          monoisotopicMass: 233.22692593467,
          charge: 0,
          mf: 'C17H29',
          atoms: { C: 17, H: 29 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
        code: '_',
      },
      {
        hose: {
          bond1: {
            atoms: [12, 13],
            from: 12,
            to: 13,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [14, 15],
            from: 14,
            to: 15,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@' },
              {
                sphere: 2,
                oclID: 'dcL@@DjefUmjjjjPJDHCa@hHhOUFIFPVUgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [13],
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: '`',
      },
      {
        hose: {
          bond1: {
            atoms: [7, 8],
            from: 7,
            to: 8,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [9, 10],
            from: 9,
            to: 10,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C17H29',
        idCode: 'fde@B@@KJSJkKJrseoNcUUUUUUP@@',
        mfInfo: {
          mass: 233.41279211211676,
          monoisotopicMass: 233.22692593467,
          charge: 0,
          mf: 'C17H29',
          atoms: { C: 17, H: 29 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
        code: 'a',
      },
      {
        hose: {
          bond1: {
            atoms: [7, 8],
            from: 7,
            to: 8,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [9, 10],
            from: 9,
            to: 10,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
        },
        atomMap: [8],
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'b',
      },
      {
        hose: {
          bond1: {
            atoms: [7, 8],
            from: 7,
            to: 8,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [10, 11],
            from: 10,
            to: 11,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C16H27',
        idCode: 'fhy@B@@KJSJkKJkNVB{uUUUUUT@@',
        mfInfo: {
          mass: 219.38617470726996,
          monoisotopicMass: 219.21127587021,
          charge: 0,
          mf: 'C16H27',
          atoms: { C: 16, H: 27 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
        code: 'c',
      },
      {
        hose: {
          bond1: {
            atoms: [7, 8],
            from: 7,
            to: 8,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
          bond2: {
            atoms: [10, 11],
            from: 10,
            to: 11,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [8],
        mf: 'C3H7',
        idCode: 'gC`H@liKT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'd',
      },
      {
        hose: {
          bond1: {
            atoms: [8, 9],
            from: 8,
            to: 9,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [10, 11],
            from: 10,
            to: 11,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [0],
        mf: 'C17H29',
        idCode: 'fde@B@@KJSJkKJrsehn}UUUUUUP@@',
        mfInfo: {
          mass: 233.41279211211676,
          monoisotopicMass: 233.22692593467,
          charge: 0,
          mf: 'C17H29',
          atoms: { C: 17, H: 29 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
        code: 'e',
      },
      {
        hose: {
          bond1: {
            atoms: [8, 9],
            from: 8,
            to: 9,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gC`@Dij@xPhIP^PrY~bPNEUGBj@' },
              { sphere: 2, oclID: 'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@' },
            ],
            length: 1,
          },
          bond2: {
            atoms: [10, 11],
            from: 10,
            to: 11,
            torsion: undefined,
            hoses: [
              { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              { sphere: 1, oclID: 'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh' },
              {
                sphere: 2,
                oclID: 'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
              },
            ],
            length: 1,
          },
        },
        atomMap: [9],
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
        code: 'f',
      },
    ]);
  });
});
