import OCL from 'openchemlib';

import { overAllFragmentation } from '../overAllFragmentation.js';

const { Molecule } = OCL;

describe('overAllFragmentation', () => {
  it('CCCCC2CCC1C(CC)CC(=O)CC1C2', () => {
    const molecule = Molecule.fromSmiles('CCCCC2CCC1C(CC)CC(=O)CC1C2'); //3 cyclohexane connected
    const result = overAllFragmentation(molecule);

    expect(result).toStrictEqual([
      [
        {
          atomMap: [0],
          hose: [
            {
              atoms: [],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'dH' },
                { sphere: 1, oclID: 'dH' },
                { sphere: 2, oclID: 'dH' },
              ],
              length: -1,
            },
          ],
          mf: 'CH3',
          idCode: 'eFBAYc@@',
          mfInfo: {
            mass: 15.03455815890258,
            monoisotopicMass: 15.02347509669,
            charge: 0,
            mf: 'CH3',
            atoms: { C: 1, H: 3 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 0,
        },
        {
          atomMap: [1],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C15H25O',
          idCode: 'fhiAB@O@VTeVUmYqRMZjjjjfh@@',
          mfInfo: {
            mass: 221.35896222674143,
            monoisotopicMass: 221.19054042532002,
            charge: 0,
            mf: 'C15H25O',
            atoms: { C: 15, H: 25, O: 1 },
            unsaturation: 3.5,
          },
          fragmentType: 'acyclic',
          code: 1,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 2, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              ],
              length: 1,
            },
          ],
          mf: 'C2H5',
          idCode: 'eMBAYRZ@',
          mfInfo: {
            mass: 29.061175563749384,
            monoisotopicMass: 29.03912516115,
            charge: 0,
            mf: 'C2H5',
            atoms: { C: 2, H: 5 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 2,
        },
        {
          atomMap: [2],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gJP@DkjhCaB`eA~bPNEUGBj@' },
              ],
              length: 1,
            },
          ],
          mf: 'C14H23O',
          idCode: 'f`qAB@G@VTeYVugxKQjjjjij@@',
          mfInfo: {
            mass: 207.33234482189462,
            monoisotopicMass: 207.17489036086002,
            charge: 0,
            mf: 'C14H23O',
            atoms: { C: 14, H: 23, O: 1 },
            unsaturation: 3.5,
          },
          fragmentType: 'acyclic',
          code: 3,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
              ],
              length: 1,
            },
          ],
          mf: 'C3H7',
          idCode: 'gC`H@liKT@@',
          mfInfo: {
            mass: 43.08779296859618,
            monoisotopicMass: 43.05477522561,
            charge: 0,
            mf: 'C3H7',
            atoms: { C: 3, H: 7 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 4,
        },
        {
          atomMap: [3],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'gC`@H}PGBEAJC}D`\\JjNET' },
                { sphere: 2, oclID: 'gGP@Djvj`NDJBTGzI@xUT\\Jh' },
              ],
              length: 1,
            },
          ],
          mf: 'C13H21O',
          idCode: 'foAAB@K@VTee[V]gEZjjjjZ`@@',
          mfInfo: {
            mass: 193.30572741704782,
            monoisotopicMass: 193.15924029640001,
            charge: 0,
            mf: 'C13H21O',
            atoms: { C: 13, H: 21, O: 1 },
            unsaturation: 3.5,
          },
          fragmentType: 'acyclic',
          code: 5,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C4H9',
          idCode: 'gJPH@liJuP@',
          mfInfo: {
            mass: 57.114410373442986,
            monoisotopicMass: 57.07042529007,
            charge: 0,
            mf: 'C4H9',
            atoms: { C: 4, H: 9 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 6,
        },
        {
          atomMap: [4],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'gC`@Dij@xPhIP_hdCaUQpj`' },
                { sphere: 2, oclID: 'gFp@DiTvjhCaB`eA~bPNEUGBj@' },
              ],
              length: 1,
            },
          ],
          mf: 'C12H19O',
          idCode: 'dg|H`CAYRYVugiiVjjjfh@@',
          mfInfo: {
            mass: 179.27911001220102,
            monoisotopicMass: 179.14359023194,
            charge: 0,
            mf: 'C12H19O',
            atoms: { C: 12, H: 19, O: 1 },
            unsaturation: 3.5,
          },
          fragmentType: 'acyclic',
          code: 7,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C14H23O',
          idCode: 'f`qAB@O@VTeUe[UdjsjjjjjZ@@',
          mfInfo: {
            mass: 207.33234482189462,
            monoisotopicMass: 207.17489036086002,
            charge: 0,
            mf: 'C14H23O',
            atoms: { C: 14, H: 23, O: 1 },
            unsaturation: 3.5,
          },
          fragmentType: 'acyclic',
          code: 8,
        },
        {
          atomMap: [9],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 2, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              ],
              length: 1,
            },
          ],
          mf: 'C2H5',
          idCode: 'eMBAYRZ@',
          mfInfo: {
            mass: 29.061175563749384,
            monoisotopicMass: 29.03912516115,
            charge: 0,
            mf: 'C2H5',
            atoms: { C: 2, H: 5 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 9,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C15H25O',
          idCode: 'fhiAB@@`VTeUe[VYJlzjjjjih@@',
          mfInfo: {
            mass: 221.35896222674143,
            monoisotopicMass: 221.19054042532002,
            charge: 0,
            mf: 'C15H25O',
            atoms: { C: 15, H: 25, O: 1 },
            unsaturation: 3.5,
          },
          fragmentType: 'acyclic',
          code: 10,
        },
        {
          atomMap: [10],
          hose: [
            {
              atoms: [],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'dH' },
                { sphere: 1, oclID: 'dH' },
                { sphere: 2, oclID: 'dH' },
              ],
              length: -1,
            },
          ],
          mf: 'CH3',
          idCode: 'eFBAYc@@',
          mfInfo: {
            mass: 15.03455815890258,
            monoisotopicMass: 15.02347509669,
            charge: 0,
            mf: 'CH3',
            atoms: { C: 1, H: 3 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 11,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C12H22O',
          idCode: 'dklH@@rIJIJEKaZjjj`@',
          mfInfo: {
            mass: 182.30293227436835,
            monoisotopicMass: 182.16706532863,
            charge: 0,
            mf: 'C12H22O',
            atoms: { C: 12, H: 22, O: 1 },
            unsaturation: 2,
          },
          fragmentType: 'cyclic',
          code: 12,
        },
        {
          atomMap: [8],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'gC`@Dij@xPhIP_hdCaUQpj`' },
                { sphere: 2, oclID: 'gC`@Dij@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C4H9',
          idCode: 'gJPH@liLuP@',
          mfInfo: {
            mass: 57.114410373442986,
            monoisotopicMass: 57.07042529007,
            charge: 0,
            mf: 'C4H9',
            atoms: { C: 4, H: 9 },
            unsaturation: 0.5,
          },
          fragmentType: 'cyclic',
          code: 13,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C11H22',
          idCode: 'dmt@@LdbRTqkjjjj@@',
          mfInfo: {
            mass: 154.29279145331483,
            monoisotopicMass: 154.17215070906,
            charge: 0,
            mf: 'C11H22',
            atoms: { C: 11, H: 22 },
            unsaturation: 1,
          },
          fragmentType: 'cyclic',
          code: 14,
        },
        {
          atomMap: [8],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'gC`@Dij@xPhIP_hdCaUQpj`' },
                { sphere: 2, oclID: 'gJP@DiZhCaB`eA~bPNEUGBj@' },
              ],
              length: 1,
            },
          ],
          mf: 'C5H9O',
          idCode: 'gNqHFEeIeZjP@',
          mfInfo: {
            mass: 85.12455119449652,
            monoisotopicMass: 85.06533990964,
            charge: 0,
            mf: 'C5H9O',
            atoms: { C: 5, H: 9, O: 1 },
            unsaturation: 1.5,
          },
          fragmentType: 'cyclic',
          code: 15,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C10H20',
          idCode: 'deT@@DjU_kjjjh@@',
          mfInfo: {
            mass: 140.26617404846803,
            monoisotopicMass: 140.1565006446,
            charge: 0,
            mf: 'C10H20',
            atoms: { C: 10, H: 20 },
            unsaturation: 1,
          },
          fragmentType: 'cyclic',
          code: 16,
        },
        {
          atomMap: [8],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'gC`@Dij@xPhIP_hdCaUQpj`' },
                { sphere: 2, oclID: 'gJP@DiZhCaB`eA~bPNEUGBj@' },
              ],
              length: 1,
            },
          ],
          mf: 'C6H11O',
          idCode: 'daxH`FAYRYVji`@',
          mfInfo: {
            mass: 99.15116859934332,
            monoisotopicMass: 99.08098997409999,
            charge: 0,
            mf: 'C6H11O',
            atoms: { C: 6, H: 11, O: 1 },
            unsaturation: 1.5,
          },
          fragmentType: 'cyclic',
          code: 17,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C14H28',
          idCode: 'dg\\@@LdbbRJrSCUUUUP@@',
          mfInfo: {
            mass: 196.37264366785524,
            monoisotopicMass: 196.21910090244,
            charge: 0,
            mf: 'C14H28',
            atoms: { C: 14, H: 28 },
            unsaturation: 1,
          },
          fragmentType: 'cyclic',
          code: 18,
        },
        {
          atomMap: [11],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eMHAIXNFhF`\x7FQR\\Ji\\Jh' },
                { sphere: 2, oclID: 'eMHAIXNFhF`\x7FQR\\Ji\\Jh' },
              ],
              length: 1,
            },
          ],
          mf: 'C2H3O',
          idCode: 'gCaHLEeIZP@',
          mfInfo: {
            mass: 43.04469897995611,
            monoisotopicMass: 43.01838971626,
            charge: 0,
            mf: 'C2H3O',
            atoms: { C: 2, H: 3, O: 1 },
            unsaturation: 1.5,
          },
          fragmentType: 'cyclic',
          code: 19,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C13H26',
          idCode: 'dkl@@DjU]Wkjjjjh@@',
          mfInfo: {
            mass: 182.3460262630084,
            monoisotopicMass: 182.20345083798,
            charge: 0,
            mf: 'C13H26',
            atoms: { C: 13, H: 26 },
            unsaturation: 1,
          },
          fragmentType: 'cyclic',
          code: 20,
        },
        {
          atomMap: [11],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'gCa@@dsPGBe@jC}Dd\\JiNET' },
                { sphere: 2, oclID: 'gCa@@dsPGBe@jC}Dd\\JiNET' },
              ],
              length: 1,
            },
          ],
          mf: 'C3H5O',
          idCode: 'gJQHLEeIZf@@',
          mfInfo: {
            mass: 57.071316384802905,
            monoisotopicMass: 57.03403978071999,
            charge: 0,
            mf: 'C3H5O',
            atoms: { C: 3, H: 5, O: 1 },
            unsaturation: 1.5,
          },
          fragmentType: 'cyclic',
          code: 21,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C14H28',
          idCode: 'dg\\@@LdbbRqRWSUUUUP@@',
          mfInfo: {
            mass: 196.37264366785524,
            monoisotopicMass: 196.21910090244,
            charge: 0,
            mf: 'C14H28',
            atoms: { C: 14, H: 28 },
            unsaturation: 1,
          },
          fragmentType: 'cyclic',
          code: 22,
        },
        {
          atomMap: [12],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eFHBJGBTEP_hhOeUNET' },
                { sphere: 1, oclID: 'eMHAIXNDhJ`\x7FQP_Jj\\Jh' },
                { sphere: 2, oclID: 'eMHAIXNDhJ`\x7FQP_Jj\\Jh' },
              ],
              length: 1,
            },
          ],
          mf: 'C2H3O',
          idCode: 'gCaHDEeIi`@',
          mfInfo: {
            mass: 43.04469897995611,
            monoisotopicMass: 43.01838971626,
            charge: 0,
            mf: 'C2H3O',
            atoms: { C: 2, H: 3, O: 1 },
            unsaturation: 1.5,
          },
          fragmentType: 'cyclic',
          code: 23,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C14H26O',
          idCode: 'do|H@@RYV]]ZYjjjjh@@',
          mfInfo: {
            mass: 210.35616708406198,
            monoisotopicMass: 210.19836545755,
            charge: 0,
            mf: 'C14H26O',
            atoms: { C: 14, H: 26, O: 1 },
            unsaturation: 2,
          },
          fragmentType: 'cyclic',
          code: 24,
        },
        {
          atomMap: [5],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 2, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              ],
              length: 1,
            },
          ],
          mf: 'C2H5',
          idCode: 'eMBAYRZ@',
          mfInfo: {
            mass: 29.061175563749384,
            monoisotopicMass: 29.03912516115,
            charge: 0,
            mf: 'C2H5',
            atoms: { C: 2, H: 5 },
            unsaturation: 0.5,
          },
          fragmentType: 'cyclic',
          code: 25,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C6H14',
          idCode: 'gGP@DiVj`@',
          mfInfo: {
            mass: 86.17558593719237,
            monoisotopicMass: 86.10955045122,
            charge: 0,
            mf: 'C6H14',
            atoms: { C: 6, H: 14 },
            unsaturation: 0,
          },
          fragmentType: 'cyclic',
          code: 26,
        },
        {
          atomMap: [5],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gJP@DkjhCaB`eA~bPNEUGBj@' },
              ],
              length: 1,
            },
          ],
          mf: 'C10H17O',
          idCode: 'dcLH`MAYRUfUqfjjjX@@',
          mfInfo: {
            mass: 153.24175671061897,
            monoisotopicMass: 153.12794016748,
            charge: 0,
            mf: 'C10H17O',
            atoms: { C: 10, H: 17, O: 1 },
            unsaturation: 2.5,
          },
          fragmentType: 'cyclic',
          code: 27,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C7H16',
          idCode: 'gNp@LdbJjj@@',
          mfInfo: {
            mass: 100.20220334203918,
            monoisotopicMass: 100.12520051568,
            charge: 0,
            mf: 'C7H16',
            atoms: { C: 7, H: 16 },
            unsaturation: 0,
          },
          fragmentType: 'cyclic',
          code: 28,
        },
        {
          atomMap: [6],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'gC`@H}PGBEAJC}D`\\JjNET' },
                { sphere: 2, oclID: 'gNp@Djyjj`hGBEAJC}D`\\JjNET' },
              ],
              length: 1,
            },
          ],
          mf: 'C9H15O',
          idCode: 'dmtH`EAYRVYWxZjjf@@',
          mfInfo: {
            mass: 139.21513930577217,
            monoisotopicMass: 139.11229010302,
            charge: 0,
            mf: 'C9H15O',
            atoms: { C: 9, H: 15, O: 1 },
            unsaturation: 2.5,
          },
          fragmentType: 'cyclic',
          code: 29,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C6H14',
          idCode: 'gGP@DiVj`@',
          mfInfo: {
            mass: 86.17558593719237,
            monoisotopicMass: 86.10955045122,
            charge: 0,
            mf: 'C6H14',
            atoms: { C: 6, H: 14 },
            unsaturation: 0,
          },
          fragmentType: 'cyclic',
          code: 30,
        },
        {
          atomMap: [6],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'gC`@H}PGBEAJC}D`\\JjNET' },
                { sphere: 2, oclID: 'dax@@Djyjjh@xPJBJC}DPGBjapj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C10H17O',
          idCode: 'dcLH`MAYrIQQQH}MUUTp@@',
          mfInfo: {
            mass: 153.24175671061897,
            monoisotopicMass: 153.12794016748,
            charge: 0,
            mf: 'C10H17O',
            atoms: { C: 10, H: 17, O: 1 },
            unsaturation: 2.5,
          },
          fragmentType: 'cyclic',
          code: 31,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C8H18',
          idCode: 'dax@@DjWzjh@@',
          mfInfo: {
            mass: 114.22882074688597,
            monoisotopicMass: 114.14085058014,
            charge: 0,
            mf: 'C8H18',
            atoms: { C: 8, H: 18 },
            unsaturation: 0,
          },
          fragmentType: 'cyclic',
          code: 32,
        },
        {
          atomMap: [7],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'gJP@DjZhCaB`eA~bPNEUGBj@' },
                { sphere: 2, oclID: 'daD@@DjUZzjjhB`NDB`b`\x7FQDApjh\\Jh' },
              ],
              length: 1,
            },
          ],
          mf: 'C8H13O',
          idCode: 'deTH`IAYRYe]njji`@',
          mfInfo: {
            mass: 125.18852190092537,
            monoisotopicMass: 125.09664003856,
            charge: 0,
            mf: 'C8H13O',
            atoms: { C: 8, H: 13, O: 1 },
            unsaturation: 2.5,
          },
          fragmentType: 'cyclic',
          code: 33,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C7H16',
          idCode: 'gNp@DiUjj@@',
          mfInfo: {
            mass: 100.20220334203918,
            monoisotopicMass: 100.12520051568,
            charge: 0,
            mf: 'C7H16',
            atoms: { C: 7, H: 16 },
            unsaturation: 0,
          },
          fragmentType: 'cyclic',
          code: 34,
        },
        {
          atomMap: [7],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'gJP@DjZhCaB`eA~bPNEUGBj@' },
                { sphere: 2, oclID: 'did@@DjUZnjjjPJBHCa@hHhOtQ@\\JjGBj@' },
              ],
              length: 1,
            },
          ],
          mf: 'C9H15O',
          idCode: 'dmtH`EAYrJJJIEajjjX@@',
          mfInfo: {
            mass: 139.21513930577217,
            monoisotopicMass: 139.11229010302,
            charge: 0,
            mf: 'C9H15O',
            atoms: { C: 9, H: 15, O: 1 },
            unsaturation: 2.5,
          },
          fragmentType: 'cyclic',
          code: 35,
        },
      ],
    ]);
  });
  it('C1CCC1', () => {
    const molecule = Molecule.fromSmiles('C1CCC1'); // just cycle
    const result = overAllFragmentation(molecule);

    expect(result).toStrictEqual([
      [
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 2, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              ],
              length: 1,
            },
          ],
          mf: 'C2H5',
          idCode: 'eMBAYRZ@',
          mfInfo: {
            mass: 29.061175563749384,
            monoisotopicMass: 29.03912516115,
            charge: 0,
            mf: 'C2H5',
            atoms: { C: 2, H: 5 },
            unsaturation: 0.5,
          },
          fragmentType: 'cyclic',
          code: 0,
        },
        {
          atomMap: [1],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 2, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              ],
              length: 1,
            },
          ],
          mf: 'C2H5',
          idCode: 'eMBAYRZ@',
          mfInfo: {
            mass: 29.061175563749384,
            monoisotopicMass: 29.03912516115,
            charge: 0,
            mf: 'C2H5',
            atoms: { C: 2, H: 5 },
            unsaturation: 0.5,
          },
          fragmentType: 'cyclic',
          code: 1,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 2, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              ],
              length: 1,
            },
          ],
          mf: 'C2H5',
          idCode: 'eMBAYRZ@',
          mfInfo: {
            mass: 29.061175563749384,
            monoisotopicMass: 29.03912516115,
            charge: 0,
            mf: 'C2H5',
            atoms: { C: 2, H: 5 },
            unsaturation: 0.5,
          },
          fragmentType: 'cyclic',
          code: 2,
        },
        {
          atomMap: [2],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 2, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              ],
              length: 1,
            },
          ],
          mf: 'C2H5',
          idCode: 'eMBAYRZ@',
          mfInfo: {
            mass: 29.061175563749384,
            monoisotopicMass: 29.03912516115,
            charge: 0,
            mf: 'C2H5',
            atoms: { C: 2, H: 5 },
            unsaturation: 0.5,
          },
          fragmentType: 'cyclic',
          code: 3,
        },
      ],
    ]);
  });
  it('CCCCCC(CC)CCC', () => {
    const molecule = Molecule.fromSmiles('CCCCCC(CC)CCC'); // just cycle
    const result = overAllFragmentation(molecule);

    expect(result).toStrictEqual([
      [
        {
          atomMap: [0],
          hose: [
            {
              atoms: [],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'dH' },
                { sphere: 1, oclID: 'dH' },
                { sphere: 2, oclID: 'dH' },
              ],
              length: -1,
            },
          ],
          mf: 'CH3',
          idCode: 'eFBAYc@@',
          mfInfo: {
            mass: 15.03455815890258,
            monoisotopicMass: 15.02347509669,
            charge: 0,
            mf: 'CH3',
            atoms: { C: 1, H: 3 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 0,
        },
        {
          atomMap: [1],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C10H21',
          idCode: 'dmT@`@VTeUeZjjh@@',
          mfInfo: {
            mass: 141.2741148025238,
            monoisotopicMass: 141.16432567683,
            charge: 0,
            mf: 'C10H21',
            atoms: { C: 10, H: 21 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 1,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 2, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              ],
              length: 1,
            },
          ],
          mf: 'C2H5',
          idCode: 'eMBAYRZ@',
          mfInfo: {
            mass: 29.061175563749384,
            monoisotopicMass: 29.03912516115,
            charge: 0,
            mf: 'C2H5',
            atoms: { C: 2, H: 5 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 2,
        },
        {
          atomMap: [2],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C9H19',
          idCode: 'ded@`@VTeVUjjj@@',
          mfInfo: {
            mass: 127.247497397677,
            monoisotopicMass: 127.14867561237,
            charge: 0,
            mf: 'C9H19',
            atoms: { C: 9, H: 19 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 3,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
              ],
              length: 1,
            },
          ],
          mf: 'C3H7',
          idCode: 'gC`H@liKT@@',
          mfInfo: {
            mass: 43.08779296859618,
            monoisotopicMass: 43.05477522561,
            charge: 0,
            mf: 'C3H7',
            atoms: { C: 3, H: 7 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 4,
        },
        {
          atomMap: [3],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gJP@DkjhCaB`eA~bPNEUGBj@' },
              ],
              length: 1,
            },
          ],
          mf: 'C8H17',
          idCode: 'diD@`@VTeYVjj`@',
          mfInfo: {
            mass: 113.22087999283019,
            monoisotopicMass: 113.13302554791,
            charge: 0,
            mf: 'C8H17',
            atoms: { C: 8, H: 17 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 5,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C4H9',
          idCode: 'gJPH@liJuP@',
          mfInfo: {
            mass: 57.114410373442986,
            monoisotopicMass: 57.07042529007,
            charge: 0,
            mf: 'C4H9',
            atoms: { C: 4, H: 9 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 6,
        },
        {
          atomMap: [4],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'gC`@H}PGBEAJC}D`\\JjNET' },
                { sphere: 2, oclID: 'gGP@Djvj`NDJBTGzI@xUT\\Jh' },
              ],
              length: 1,
            },
          ],
          mf: 'C7H15',
          idCode: 'dax@`@VTeeZjh@@',
          mfInfo: {
            mass: 99.1942625879834,
            monoisotopicMass: 99.11737548345,
            charge: 0,
            mf: 'C7H15',
            atoms: { C: 7, H: 15 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 7,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C5H11',
          idCode: 'gGPH@liJmU@@',
          mfInfo: {
            mass: 71.1410277782898,
            monoisotopicMass: 71.08607535453,
            charge: 0,
            mf: 'C5H11',
            atoms: { C: 5, H: 11 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 8,
        },
        {
          atomMap: [5],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'gC`@Dij@xPhIP_hdCaUQpj`' },
                { sphere: 2, oclID: 'gJP@DiZhCaB`eA~bPNEUGBj@' },
              ],
              length: 1,
            },
          ],
          mf: 'C6H13',
          idCode: 'gNpH@liLkUT@@',
          mfInfo: {
            mass: 85.16764518313659,
            monoisotopicMass: 85.10172541899,
            charge: 0,
            mf: 'C6H13',
            atoms: { C: 6, H: 13 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 9,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C9H19',
          idCode: 'ded@`@VTeUUjjj@@',
          mfInfo: {
            mass: 127.247497397677,
            monoisotopicMass: 127.14867561237,
            charge: 0,
            mf: 'C9H19',
            atoms: { C: 9, H: 19 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 10,
        },
        {
          atomMap: [6],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 2, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              ],
              length: 1,
            },
          ],
          mf: 'C2H5',
          idCode: 'eMBAYRZ@',
          mfInfo: {
            mass: 29.061175563749384,
            monoisotopicMass: 29.03912516115,
            charge: 0,
            mf: 'C2H5',
            atoms: { C: 2, H: 5 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 11,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C10H21',
          idCode: 'dmT@`@VTeUYzjjh@@',
          mfInfo: {
            mass: 141.2741148025238,
            monoisotopicMass: 141.16432567683,
            charge: 0,
            mf: 'C10H21',
            atoms: { C: 10, H: 21 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 12,
        },
        {
          atomMap: [7],
          hose: [
            {
              atoms: [],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'dH' },
                { sphere: 1, oclID: 'dH' },
                { sphere: 2, oclID: 'dH' },
              ],
              length: -1,
            },
          ],
          mf: 'CH3',
          idCode: 'eFBAYc@@',
          mfInfo: {
            mass: 15.03455815890258,
            monoisotopicMass: 15.02347509669,
            charge: 0,
            mf: 'CH3',
            atoms: { C: 1, H: 3 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 13,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C8H17',
          idCode: 'diD@`@VTeUVjj`@',
          mfInfo: {
            mass: 113.22087999283019,
            monoisotopicMass: 113.13302554791,
            charge: 0,
            mf: 'C8H17',
            atoms: { C: 8, H: 17 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 14,
        },
        {
          atomMap: [8],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
              ],
              length: 1,
            },
          ],
          mf: 'C3H7',
          idCode: 'gC`H@liKT@@',
          mfInfo: {
            mass: 43.08779296859618,
            monoisotopicMass: 43.05477522561,
            charge: 0,
            mf: 'C3H7',
            atoms: { C: 3, H: 7 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 15,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C9H19',
          idCode: 'ded@`@VTeUYjjj@@',
          mfInfo: {
            mass: 127.247497397677,
            monoisotopicMass: 127.14867561237,
            charge: 0,
            mf: 'C9H19',
            atoms: { C: 9, H: 19 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 16,
        },
        {
          atomMap: [9],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 2, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
              ],
              length: 1,
            },
          ],
          mf: 'C2H5',
          idCode: 'eMBAYRZ@',
          mfInfo: {
            mass: 29.061175563749384,
            monoisotopicMass: 29.03912516115,
            charge: 0,
            mf: 'C2H5',
            atoms: { C: 2, H: 5 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 17,
        },
        {
          atomMap: [0],
          hose: [
            {
              atoms: [0, 1],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'eF@Hp\\IPUA~b`xUTxUP' },
                { sphere: 1, oclID: 'eM@HzCaJBhOtTGBjgBj@' },
                { sphere: 2, oclID: 'gC`@Dkj@xPhIP_hdCaUQpj`' },
              ],
              length: 1,
            },
          ],
          mf: 'C10H21',
          idCode: 'dmT@`@VTeUYZjjh@@',
          mfInfo: {
            mass: 141.2741148025238,
            monoisotopicMass: 141.16432567683,
            charge: 0,
            mf: 'C10H21',
            atoms: { C: 10, H: 21 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 18,
        },
        {
          atomMap: [10],
          hose: [
            {
              atoms: [],
              from: 0,
              to: 1,
              torsion: undefined,
              hoses: [
                { sphere: 0, oclID: 'dH' },
                { sphere: 1, oclID: 'dH' },
                { sphere: 2, oclID: 'dH' },
              ],
              length: -1,
            },
          ],
          mf: 'CH3',
          idCode: 'eFBAYc@@',
          mfInfo: {
            mass: 15.03455815890258,
            monoisotopicMass: 15.02347509669,
            charge: 0,
            mf: 'CH3',
            atoms: { C: 1, H: 3 },
            unsaturation: 0.5,
          },
          fragmentType: 'acyclic',
          code: 19,
        },
      ],
    ]);
  });
  it('noMolecule', () => {
    const molecule = Molecule.fromSmiles('');
    const result = overAllFragmentation(molecule);

    expect(result).toStrictEqual([[]]);
  });
});
