import OCL from 'openchemlib';

import { fragmentCyclicBonds } from '../../fragmentCyclicBonds.js';

const { Molecule } = OCL;

describe('fragmentCyclicBonds', () => {
  it('CCCC', () => {
    const molecule = Molecule.fromSmiles('CCCC'); // butane
    const result = fragmentCyclicBonds(molecule);

    expect(result).toStrictEqual([]);
  });
  it('C1CC1', () => {
    const molecule = Molecule.fromSmiles('C1CC1'); // butane
    const result = fragmentCyclicBonds(molecule);
    expect(result).toStrictEqual([]);
  });

  it('c1ccncc1', () => {
    const molecule = Molecule.fromSmiles('c1ccncc1'); // benzene
    const result = fragmentCyclicBonds(molecule);

    expect(result).toStrictEqual([]);
  });

  it('CCC13CCCC2CCCC(CCC1)C23', () => {
    const molecule = Molecule.fromSmiles('C1CC2CCCC3CCCC(C1)C23'); //3 cyclohexane connected
    const result = fragmentCyclicBonds(molecule);

    expect(result).toStrictEqual([
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'deT@@DiYUIjjjkDhJab@xPJBJCwAdXdYaQVMGzH`NEUCaU@',
            'dk|@@DiYU[IaWSjjjjjIJBhXcb@xPJBJCradXdYaQVMGPNSgzH`NEUCaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
        },
        atomMap: [0],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'deT@@DiYUIjjjkDhJab@xPJBJCwAdXdYaQVMGzH`NEUCaU@',
            'dk|@@DiYU[IaWSjjjjjIJBhXcb@xPJBJCradXdYaQVMGPNSgzH`NEUCaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
        },
        atomMap: [1],
        smiles: 'CC1(CCCC2(CCCCC12))',
        mf: 'C11H19',
        idCode: 'dcl@`@V\\bTTRbOBnuUUUP@@',
        mfInfo: {
          mass: 151.2689691911475,
          monoisotopicMass: 151.14867561237,
          charge: 0,
          mf: 'C11H19',
          atoms: { C: 11, H: 19 },
          unsaturation: 2.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
        },
        atomMap: [0],
        smiles: 'C(C)C',
        mf: 'C3H7',
        idCode: 'gC`H@liMT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
        },
        atomMap: [2],
        smiles: 'C1(CCCC2(CCCCC12))',
        mf: 'C10H17',
        idCode: 'dmL@`@V\\bbbTQ[iVjjjh@@',
        mfInfo: {
          mass: 137.2423517863007,
          monoisotopicMass: 137.13302554791,
          charge: 0,
          mf: 'C10H17',
          atoms: { C: 10, H: 17 },
          unsaturation: 2.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'deT@@DiYUIjjjkDhJab@xPJBJCwAdXdYaQVMGzH`NEUCaU@',
            'dk|@@DiYU[IaWSjjjjjIJBhXcb@xPJBJCradXdYaQVMGPNSgzH`NEUCaU@',
          ],
        },
        atomMap: [0],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'deT@@DiYUIjjjkDhJab@xPJBJCwAdXdYaQVMGzH`NEUCaU@',
            'dk|@@DiYU[IaWSjjjjjIJBhXcb@xPJBJCradXdYaQVMGPNSgzH`NEUCaU@',
          ],
        },
        atomMap: [2],
        smiles: 'C1(CCCC2(CCCC(C)C12))',
        mf: 'C11H19',
        idCode: 'dcl@`@V\\bbbTTK]NuUUUP@@',
        mfInfo: {
          mass: 151.2689691911475,
          monoisotopicMass: 151.14867561237,
          charge: 0,
          mf: 'C11H19',
          atoms: { C: 11, H: 19 },
          unsaturation: 2.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'deT@@DiYUIjjjkDhJab@xPJBJCwAdXdYaQVMGzH`NEUCaU@',
            'dk|@@DiYU[IaWSjjjjjIJBhXcb@xPJBJCradXdYaQVMGPNSgzH`NEUCaU@',
          ],
        },
        atomMap: [0],
        smiles: 'C1(CC2(CCCCC2(C(C)C1)))',
        mf: 'C11H19',
        idCode: 'dcl@`@VTfUe^fWZjjjh@@',
        mfInfo: {
          mass: 151.2689691911475,
          monoisotopicMass: 151.14867561237,
          charge: 0,
          mf: 'C11H19',
          atoms: { C: 11, H: 19 },
          unsaturation: 2.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'deT@@DiYUIjjjkDhJab@xPJBJCwAdXdYaQVMGzH`NEUCaU@',
            'dk|@@DiYU[IaWSjjjjjIJBhXcb@xPJBJCradXdYaQVMGPNSgzH`NEUCaU@',
          ],
        },
        atomMap: [7],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
        },
        atomMap: [0],
        smiles: 'C1(CC2(CCCCC2(CC1)))',
        mf: 'C10H17',
        idCode: 'dmL@`@VTfUmZZUjjjj@@',
        mfInfo: {
          mass: 137.2423517863007,
          monoisotopicMass: 137.13302554791,
          charge: 0,
          mf: 'C10H17',
          atoms: { C: 10, H: 17 },
          unsaturation: 2.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
        },
        atomMap: [7],
        smiles: 'CCC',
        mf: 'C3H7',
        idCode: 'gC`H@liKT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'deT@@DiYUIjjjkDhJab@xPJBJCwAdXdYaQVMGzH`NEUCaU@',
            'dk|@@DiYU[IaWSjjjjjIJBhXcb@xPJBJCradXdYaQVMGPNSgzH`NEUCaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
        },
        atomMap: [0],
        smiles: 'C1(CC2(CCCC(C)C2(CC1)))',
        mf: 'C11H19',
        idCode: 'dcl@`@VTfUmZfeZjjjh@@',
        mfInfo: {
          mass: 151.2689691911475,
          monoisotopicMass: 151.14867561237,
          charge: 0,
          mf: 'C11H19',
          atoms: { C: 11, H: 19 },
          unsaturation: 2.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'deT@@DiYUIjjjkDhJab@xPJBJCwAdXdYaQVMGzH`NEUCaU@',
            'dk|@@DiYU[IaWSjjjjjIJBhXcb@xPJBJCradXdYaQVMGPNSgzH`NEUCaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
        },
        atomMap: [8],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'deT@@DiYUIjjjkDhJab@xPJBJCwAdXdYaQVMGzH`NEUCaU@',
            'dk|@@DiYU[IaWSjjjjjIJBhXcb@xPJBJCradXdYaQVMGPNSgzH`NEUCaU@',
          ],
        },
        atomMap: [0],
        smiles: 'C2(CCC1(C(CCCC1(C))C2))',
        mf: 'C11H19',
        idCode: 'dcl@`@VTfUmZfeZjjjh@@',
        mfInfo: {
          mass: 151.2689691911475,
          monoisotopicMass: 151.14867561237,
          charge: 0,
          mf: 'C11H19',
          atoms: { C: 11, H: 19 },
          unsaturation: 2.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'deT@@DiYUIjjjkDhJab@xPJBJCwAdXdYaQVMGzH`NEUCaU@',
            'dk|@@DiYU[IaWSjjjjjIJBhXcb@xPJBJCradXdYaQVMGPNSgzH`NEUCaU@',
          ],
        },
        atomMap: [3],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
        },
        atomMap: [0],
        smiles: 'C2(CCC1(C(CCCC1)C2))',
        mf: 'C10H17',
        idCode: 'dmL@`@VTfUmZZUjjjj@@',
        mfInfo: {
          mass: 137.2423517863007,
          monoisotopicMass: 137.13302554791,
          charge: 0,
          mf: 'C10H17',
          atoms: { C: 10, H: 17 },
          unsaturation: 2.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
        },
        atomMap: [3],
        smiles: 'CCC',
        mf: 'C3H7',
        idCode: 'gC`H@liKT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'deT@@DiYUIjjjkDhJab@xPJBJCwAdXdYaQVMGzH`NEUCaU@',
            'dk|@@DiYU[IaWSjjjjjIJBhXcb@xPJBJCradXdYaQVMGPNSgzH`NEUCaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
        },
        atomMap: [0],
        smiles: 'C2(CC(C)C1(C(CCCC1)C2))',
        mf: 'C11H19',
        idCode: 'dcl@`@VTfUe^fWZjjjh@@',
        mfInfo: {
          mass: 151.2689691911475,
          monoisotopicMass: 151.14867561237,
          charge: 0,
          mf: 'C11H19',
          atoms: { C: 11, H: 19 },
          unsaturation: 2.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'deT@@DiYUIjjjkDhJab@xPJBJCwAdXdYaQVMGzH`NEUCaU@',
            'dk|@@DiYU[IaWSjjjjjIJBhXcb@xPJBJCradXdYaQVMGPNSgzH`NEUCaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dcl@@DjVUZayZjjjh`hRbjFHCa@hHhORDQbQfEePt]`y~bHCaUPxUP',
            'dk|@@LdbTRRah^WSjjjjjHJDhjab@xPJBJCqaDXdYaYTMGXNSbyn_hb@xUTNET',
          ],
        },
        atomMap: [4],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
    ]);
  });

  it('C2CCC1CCCCC1C2', () => {
    const molecule = Molecule.fromSmiles('C2CCC1CCCCC1C2'); //2 cyclohexane
    const result = fragmentCyclicBonds(molecule);
    expect(result).toStrictEqual([
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gFp@DiTvjhCaB`eAxcIbsY~bPNEUGBj@',
            'daD@@DiURjjjdJT`xPJBJCsAdXfYaQT_hb@xUTNET',
            'det@@DiUUJafjjjdJT`xPJBJCpadXfYaQTMgY~bHCaUPxUP',
          ],
        },
        atomMap: [0],
        smiles: 'C1(CCCC(CC)C1)',
        mf: 'C8H15',
        idCode: 'did@`@V\\bbRaijjj`@',
        mfInfo: {
          mass: 111.20499848471864,
          monoisotopicMass: 111.11737548345,
          charge: 0,
          mf: 'C8H15',
          atoms: { C: 8, H: 15 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gFp@DiTvjhCaB`eAxcIbsY~bPNEUGBj@',
            'daD@@DiURjjjdJT`xPJBJCsAdXfYaQT_hb@xUTNET',
            'det@@DiUUJafjjjdJT`xPJBJCpadXfYaQTMgY~bHCaUPxUP',
          ],
        },
        atomMap: [4],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'did@@DiYTfjjjQJBhCa@hHhO\\FQbQfEEXv_hb@xUTNET',
            'det@@DiYWIafjjjdR`j@xPJBJCtadXdYaQVMgXN_hb@xUTNET',
          ],
        },
        atomMap: [0],
        smiles: 'C1(CCCC(C)C1)',
        mf: 'C7H13',
        idCode: 'daD@`@VTfUjZjj`@',
        mfInfo: {
          mass: 97.17838107987185,
          monoisotopicMass: 97.10172541899,
          charge: 0,
          mf: 'C7H13',
          atoms: { C: 7, H: 13 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'did@@DiYTfjjjQJBhCa@hHhO\\FQbQfEEXv_hb@xUTNET',
            'det@@DiYWIafjjjdR`j@xPJBJCtadXdYaQVMgXN_hb@xUTNET',
          ],
        },
        atomMap: [4],
        smiles: 'CCC',
        mf: 'C3H7',
        idCode: 'gC`H@liKT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
        },
        atomMap: [0],
        smiles: 'C1(CCCCC1)',
        mf: 'C6H11',
        idCode: 'gOpH@liLkWUU@@',
        mfInfo: {
          mass: 83.15176367502504,
          monoisotopicMass: 83.08607535453,
          charge: 0,
          mf: 'C6H11',
          atoms: { C: 6, H: 11 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
        },
        atomMap: [4],
        smiles: 'CCCC',
        mf: 'C4H9',
        idCode: 'gJPH@liJuP@',
        mfInfo: {
          mass: 57.114410373442986,
          monoisotopicMass: 57.07042529007,
          charge: 0,
          mf: 'C4H9',
          atoms: { C: 4, H: 9 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'did@@DiYTfjjjQJBhCa@hHhO\\FQbQfEEXv_hb@xUTNET',
            'det@@DiYWIafjjjdR`j@xPJBJCtadXdYaQVMgXN_hb@xUTNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'did@@DiYTfjjjQJBhCa@hHhO\\FQbQfEEXv_hb@xUTNET',
            'det@@DiYWIafjjjdR`j@xPJBJCtadXdYaQVMgXN_hb@xUTNET',
          ],
        },
        atomMap: [0],
        smiles: 'C1(CCC(C)C(C)C1)',
        mf: 'C8H15',
        idCode: 'did@`@VTfUnfjjj@@',
        mfInfo: {
          mass: 111.20499848471864,
          monoisotopicMass: 111.11737548345,
          charge: 0,
          mf: 'C8H15',
          atoms: { C: 8, H: 15 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'did@@DiYTfjjjQJBhCa@hHhO\\FQbQfEEXv_hb@xUTNET',
            'det@@DiYWIafjjjdR`j@xPJBJCtadXdYaQVMgXN_hb@xUTNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'did@@DiYTfjjjQJBhCa@hHhO\\FQbQfEEXv_hb@xUTNET',
            'det@@DiYWIafjjjdR`j@xPJBJCtadXdYaQVMgXN_hb@xUTNET',
          ],
        },
        atomMap: [5],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'did@@DiYTfjjjQJBhCa@hHhO\\FQbQfEEXv_hb@xUTNET',
            'det@@DiYWIafjjjdR`j@xPJBJCtadXdYaQVMgXN_hb@xUTNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
        },
        atomMap: [0],
        smiles: 'C1(CCC(C)CC1)',
        mf: 'C7H13',
        idCode: 'daD@`@VTfUzZjj`@',
        mfInfo: {
          mass: 97.17838107987185,
          monoisotopicMass: 97.10172541899,
          charge: 0,
          mf: 'C7H13',
          atoms: { C: 7, H: 13 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'did@@DiYTfjjjQJBhCa@hHhO\\FQbQfEEXv_hb@xUTNET',
            'det@@DiYWIafjjjdR`j@xPJBJCtadXdYaQVMgXN_hb@xUTNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
        },
        atomMap: [5],
        smiles: 'CCC',
        mf: 'C3H7',
        idCode: 'gC`H@liKT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gFp@DiTvjhCaB`eAxcIbsY~bPNEUGBj@',
            'daD@@DiURjjjdJT`xPJBJCsAdXfYaQT_hb@xUTNET',
            'det@@DiUUJafjjjdJT`xPJBJCpadXfYaQTMgY~bHCaUPxUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
        },
        atomMap: [0],
        smiles: 'C1(CCC(CC)CC1)',
        mf: 'C8H15',
        idCode: 'did@`@VTfUvfjjj@@',
        mfInfo: {
          mass: 111.20499848471864,
          monoisotopicMass: 111.11737548345,
          charge: 0,
          mf: 'C8H15',
          atoms: { C: 8, H: 15 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gFp@DiTvjhCaB`eAxcIbsY~bPNEUGBj@',
            'daD@@DiURjjjdJT`xPJBJCsAdXfYaQT_hb@xUTNET',
            'det@@DiUUJafjjjdJT`xPJBJCpadXfYaQTMgY~bHCaUPxUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
        },
        atomMap: [6],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gFp@DiTvjhCaB`eAxcIbsY~bPNEUGBj@',
            'daD@@DiURjjjdJT`xPJBJCsAdXfYaQT_hb@xUTNET',
            'det@@DiUUJafjjjdJT`xPJBJCpadXfYaQTMgY~bHCaUPxUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
        },
        atomMap: [0],
        smiles: 'CCC1(CCCCC1)',
        mf: 'C8H15',
        idCode: 'did@`@VTeYWajjj@@',
        mfInfo: {
          mass: 111.20499848471864,
          monoisotopicMass: 111.11737548345,
          charge: 0,
          mf: 'C8H15',
          atoms: { C: 8, H: 15 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gFp@DiTvjhCaB`eAxcIbsY~bPNEUGBj@',
            'daD@@DiURjjjdJT`xPJBJCsAdXfYaQT_hb@xUTNET',
            'det@@DiUUJafjjjdJT`xPJBJCpadXfYaQTMgY~bHCaUPxUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
        },
        atomMap: [1],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gFp@DiTvjhCaB`eAxcIbsY~bPNEUGBj@',
            'daD@@DiURjjjdJT`xPJBJCsAdXfYaQT_hb@xUTNET',
            'det@@DiUUJafjjjdJT`xPJBJCpadXfYaQTMgY~bHCaUPxUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
        },
        atomMap: [0],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gFp@DiTvjhCaB`eAxcIbsY~bPNEUGBj@',
            'daD@@DiURjjjdJT`xPJBJCsAdXfYaQT_hb@xUTNET',
            'det@@DiUUJafjjjdJT`xPJBJCpadXfYaQTMgY~bHCaUPxUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
        },
        atomMap: [1],
        smiles: 'CCC1(CCCCC1)',
        mf: 'C8H15',
        idCode: 'did@`@VTeYWajjj@@',
        mfInfo: {
          mass: 111.20499848471864,
          monoisotopicMass: 111.11737548345,
          charge: 0,
          mf: 'C8H15',
          atoms: { C: 8, H: 15 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'did@@DiYTfjjjQJBhCa@hHhO\\FQbQfEEXv_hb@xUTNET',
            'det@@DiYWIafjjjdR`j@xPJBJCtadXdYaQVMgXN_hb@xUTNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
        },
        atomMap: [0],
        smiles: 'C(C)C',
        mf: 'C3H7',
        idCode: 'gC`H@liMT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'did@@DiYTfjjjQJBhCa@hHhO\\FQbQfEEXv_hb@xUTNET',
            'det@@DiYWIafjjjdR`j@xPJBJCtadXdYaQVMgXN_hb@xUTNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
        },
        atomMap: [2],
        smiles: 'CC1(CCCCC1)',
        mf: 'C7H13',
        idCode: 'daD@`@VTeeVzjj`@',
        mfInfo: {
          mass: 97.17838107987185,
          monoisotopicMass: 97.10172541899,
          charge: 0,
          mf: 'C7H13',
          atoms: { C: 7, H: 13 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'did@@DiYTfjjjQJBhCa@hHhO\\FQbQfEEXv_hb@xUTNET',
            'det@@DiYWIafjjjdR`j@xPJBJCtadXdYaQVMgXN_hb@xUTNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'did@@DiYTfjjjQJBhCa@hHhO\\FQbQfEEXv_hb@xUTNET',
            'det@@DiYWIafjjjdR`j@xPJBJCtadXdYaQVMgXN_hb@xUTNET',
          ],
        },
        atomMap: [0],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'did@@DiYTfjjjQJBhCa@hHhO\\FQbQfEEXv_hb@xUTNET',
            'det@@DiYWIafjjjdR`j@xPJBJCtadXdYaQVMgXN_hb@xUTNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'did@@DiYTfjjjQJBhCa@hHhO\\FQbQfEEXv_hb@xUTNET',
            'det@@DiYWIafjjjdR`j@xPJBJCtadXdYaQVMgXN_hb@xUTNET',
          ],
        },
        atomMap: [2],
        smiles: 'CC1(CCCCC1C)',
        mf: 'C8H15',
        idCode: 'did@`@VTefWajjj@@',
        mfInfo: {
          mass: 111.20499848471864,
          monoisotopicMass: 111.11737548345,
          charge: 0,
          mf: 'C8H15',
          atoms: { C: 8, H: 15 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
        },
        atomMap: [0],
        smiles: 'C(CC)C',
        mf: 'C4H9',
        idCode: 'gJPH@liLuP@',
        mfInfo: {
          mass: 57.114410373442986,
          monoisotopicMass: 57.07042529007,
          charge: 0,
          mf: 'C4H9',
          atoms: { C: 4, H: 9 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
        },
        atomMap: [3],
        smiles: 'C1(CCCCC1)',
        mf: 'C6H11',
        idCode: 'gOpH@liLkWUU@@',
        mfInfo: {
          mass: 83.15176367502504,
          monoisotopicMass: 83.08607535453,
          charge: 0,
          mf: 'C6H11',
          atoms: { C: 6, H: 11 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'did@@DiYTfjjjQJBhCa@hHhO\\FQbQfEEXv_hb@xUTNET',
            'det@@DiYWIafjjjdR`j@xPJBJCtadXdYaQVMgXN_hb@xUTNET',
          ],
        },
        atomMap: [0],
        smiles: 'CCC',
        mf: 'C3H7',
        idCode: 'gC`H@liKT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'det@@DjVWh^fjjjdBaJ@xPJBJCtaDXdYaYVMgXN_hb@xUTNET',
            'det@@DjVWh^fjjjdBaJ@XPJBJC}DPGBjapj`',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'did@@DiYTfjjjQJBhCa@hHhO\\FQbQfEEXv_hb@xUTNET',
            'det@@DiYWIafjjjdR`j@xPJBJCtadXdYaQVMgXN_hb@xUTNET',
          ],
        },
        atomMap: [3],
        smiles: 'C1(CCCCC1C)',
        mf: 'C7H13',
        idCode: 'daD@`@VTfYVzjj`@',
        mfInfo: {
          mass: 97.17838107987185,
          monoisotopicMass: 97.10172541899,
          charge: 0,
          mf: 'C7H13',
          atoms: { C: 7, H: 13 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
      },
    ]);

    // Bug: getRingSet do not reconise rings with less than 6 carbons and with more than 7
  });
  it('C2CCC1CCCC3CCCC4CCCC1', () => {
    const molecule = Molecule.fromSmiles('C2CCC1CCCC3CCCC4CCCC1(CC2)C34'); //4 cycles (2 hexane & 2 heptane)
    const result = fragmentCyclicBonds(molecule);

    expect(result).toStrictEqual([
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh',
            'daD@@DiUjZjjhJ`NDB`b`|pYFIfXTUgzH`NEUCaU@',
            'dmt@@DiUnZZjjjhH`NDB`b`}pYFIfXTUgY~bHCaUPxUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@',
            'foA@@@DjVeYVQeNjjjjjl@hPQP`GB@TDJCt`QCLXSJPsNXKIY~bD@xUTGBj@',
            'fde@@@DjVeYWZQeNlFjjjjjjj@hPQPaQFj@\\HAPPhONADLqaLiCLy`lebhuAlmcl\x7FQB@\\JjCaU@',
          ],
        },
        atomMap: [0],
        smiles: 'CCCC12(CCCC3(CCCC(CCCC1)C23))',
        mf: 'C17H29',
        idCode: 'fde@B@@KNQIJQQIQQGScA}Fjjjjjj`@@',
        mfInfo: {
          mass: 233.41279211211676,
          monoisotopicMass: 233.22692593467,
          charge: 0,
          mf: 'C17H29',
          atoms: { C: 17, H: 29 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh',
            'daD@@DiUjZjjhJ`NDB`b`|pYFIfXTUgzH`NEUCaU@',
            'dmt@@DiUnZZjjjhH`NDB`b`}pYFIfXTUgY~bHCaUPxUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@',
            'foA@@@DjVeYVQeNjjjjjl@hPQP`GB@TDJCt`QCLXSJPsNXKIY~bD@xUTGBj@',
            'fde@@@DjVeYWZQeNlFjjjjjjj@hPQPaQFj@\\HAPPhONADLqaLiCLy`lebhuAlmcl\x7FQB@\\JjCaU@',
          ],
        },
        atomMap: [1],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh',
            'daD@@DiUjZjjhJ`NDB`b`|pYFIfXTUgzH`NEUCaU@',
            'dmt@@DiUnZZjjjhH`NDB`b`}pYFIfXTUgY~bHCaUPxUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@',
            'dct@@DjefVjjj`Ca@hHhOUFIFPVUgzH`NEUCaU@',
            'fde@@@DjefUVYP]Flzjjjjjjj@hQQb`UDb@\\HAPPhOZabHqALicLy`heBlugzHPCaUP\\Jh',
            'flm@@@LddRbbRRbgTGUcNbfjjjjjjjhBaAFJATRHAp`EAB`}FFHcDDrfLsfBbTJsVFrvNsvArN_ha@NEUApj`',
          ],
        },
        atomMap: [0],
        smiles: 'CCC',
        mf: 'C3H7',
        idCode: 'gC`H@liKT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh',
            'daD@@DiUjZjjhJ`NDB`b`|pYFIfXTUgzH`NEUCaU@',
            'dmt@@DiUnZZjjjhH`NDB`b`}pYFIfXTUgY~bHCaUPxUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@',
            'dct@@DjefVjjj`Ca@hHhOUFIFPVUgzH`NEUCaU@',
            'fde@@@DjefUVYP]Flzjjjjjjj@hQQb`UDb@\\HAPPhOZabHqALicLy`heBlugzHPCaUP\\Jh',
            'flm@@@LddRbbRRbgTGUcNbfjjjjjjjhBaAFJATRHAp`EAB`}FFHcDDrfLsfBbTJsVFrvNsvArN_ha@NEUApj`',
          ],
        },
        atomMap: [1],
        smiles: 'CCC1(CCCC2(CCCC3(CCCC1C23)))',
        mf: 'C16H27',
        idCode: 'fhy@B@@KNQIQQJIIPrMiw`uUUUUUP@@',
        mfInfo: {
          mass: 219.38617470726996,
          monoisotopicMass: 219.21127587021,
          charge: 0,
          mf: 'C16H27',
          atoms: { C: 16, H: 27 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh',
            'daD@@DiUjZjjhJ`NDB`b`|pYFIfXTUgzH`NEUCaU@',
            'dmt@@DiUnZZjjjhH`NDB`b`}pYFIfXTUgY~bHCaUPxUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'dax@@DiZZjh@xPJBJCvAdYf_hb@xUTNET',
            'dkl@@DiZVYxZjjjiDhJ`NDB`b`}pYFYaQTMgY~bHCaUPxUP',
            'fde@@@LdRdRbbJbgAFCYuUUUUUUTQPRbeBjMD@xPB`aP^LCHYcBQRFYsAYKEQjCY~bD@xUTGBj@',
          ],
        },
        atomMap: [0],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh',
            'daD@@DiUjZjjhJ`NDB`b`|pYFIfXTUgzH`NEUCaU@',
            'dmt@@DiUnZZjjjhH`NDB`b`}pYFIfXTUgY~bHCaUPxUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'dax@@DiZZjh@xPJBJCvAdYf_hb@xUTNET',
            'dkl@@DiZVYxZjjjiDhJ`NDB`b`}pYFYaQTMgY~bHCaUPxUP',
            'fde@@@LdRdRbbJbgAFCYuUUUUUUTQPRbeBjMD@xPB`aP^LCHYcBQRFYsAYKEQjCY~bD@xUTGBj@',
          ],
        },
        atomMap: [1],
        smiles: 'CCC1(CCCC2(CCCC3(CCCC1(C)C23)))',
        mf: 'C17H29',
        idCode: 'fde@B@@KNQIQRIQYJEUc^CFjjjjjj`@@',
        mfInfo: {
          mass: 233.41279211211676,
          monoisotopicMass: 233.22692593467,
          charge: 0,
          mf: 'C17H29',
          atoms: { C: 17, H: 29 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`',
            'dmt@@DiYZVzjjjhR`NDB`b`|pYFIFYVMgzH`NEUCaU@',
            'foA@@@DiYZ^u`mNjjjjjlHHIQr`GB@TDJCr`YCDQcJXsNPKIXkOtP`GBj`xUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@',
            'dct@@DjefVjjj`Ca@hHhOUFIFPVUgzH`NEUCaU@',
            'fde@@@DjefUVYP]Flzjjjjjjj@hQQb`UDb@\\HAPPhOZabHqALicLy`heBlugzHPCaUP\\Jh',
            'flm@@@LddRbbRRbgTGUcNbfjjjjjjjhBaAFJATRHAp`EAB`}FFHcDDrfLsfBbTJsVFrvNsvArN_ha@NEUApj`',
          ],
        },
        atomMap: [0],
        smiles: 'C(C)CC',
        mf: 'C4H9',
        idCode: 'gJPH@liLuP@',
        mfInfo: {
          mass: 57.114410373442986,
          monoisotopicMass: 57.07042529007,
          charge: 0,
          mf: 'C4H9',
          atoms: { C: 4, H: 9 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`',
            'dmt@@DiYZVzjjjhR`NDB`b`|pYFIFYVMgzH`NEUCaU@',
            'foA@@@DiYZ^u`mNjjjjjlHHIQr`GB@TDJCr`YCDQcJXsNPKIXkOtP`GBj`xUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@',
            'dct@@DjefVjjj`Ca@hHhOUFIFPVUgzH`NEUCaU@',
            'fde@@@DjefUVYP]Flzjjjjjjj@hQQb`UDb@\\HAPPhOZabHqALicLy`heBlugzHPCaUP\\Jh',
            'flm@@@LddRbbRRbgTGUcNbfjjjjjjjhBaAFJATRHAp`EAB`}FFHcDDrfLsfBbTJsVFrvNsvArN_ha@NEUApj`',
          ],
        },
        atomMap: [2],
        smiles: 'CC1(CCCC2(CCCC3(CCCC1C23)))',
        mf: 'C15H25',
        idCode: 'f`i@B@@KNQJJIQIJDVeV]zjjjjjh@@',
        mfInfo: {
          mass: 205.35955730242316,
          monoisotopicMass: 205.19562580575,
          charge: 0,
          mf: 'C15H25',
          atoms: { C: 15, H: 25 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`',
            'dmt@@DiYZVzjjjhR`NDB`b`|pYFIFYVMgzH`NEUCaU@',
            'foA@@@DiYZ^u`mNjjjjjlHHIQr`GB@TDJCr`YCDQcJXsNPKIXkOtP`GBj`xUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'dax@@DiZZjh@xPJBJCvAdYf_hb@xUTNET',
            'dkl@@DiZVYxZjjjiDhJ`NDB`b`}pYFYaQTMgY~bHCaUPxUP',
            'fde@@@LdRdRbbJbgAFCYuUUUUUUTQPRbeBjMD@xPB`aP^LCHYcBQRFYsAYKEQjCY~bD@xUTGBj@',
          ],
        },
        atomMap: [0],
        smiles: 'C(C)C',
        mf: 'C3H7',
        idCode: 'gC`H@liMT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`',
            'dmt@@DiYZVzjjjhR`NDB`b`|pYFIFYVMgzH`NEUCaU@',
            'foA@@@DiYZ^u`mNjjjjjlHHIQr`GB@TDJCr`YCDQcJXsNPKIXkOtP`GBj`xUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'dax@@DiZZjh@xPJBJCvAdYf_hb@xUTNET',
            'dkl@@DiZVYxZjjjiDhJ`NDB`b`}pYFYaQTMgY~bHCaUPxUP',
            'fde@@@LdRdRbbJbgAFCYuUUUUUUTQPRbeBjMD@xPB`aP^LCHYcBQRFYsAYKEQjCY~bD@xUTGBj@',
          ],
        },
        atomMap: [2],
        smiles: 'CC1(CCCC2(CCCC3(CCCC1(C)C23)))',
        mf: 'C16H27',
        idCode: 'fhy@B@@KNQJJQJKIPrMiw`uUUUUUP@@',
        mfInfo: {
          mass: 219.38617470726996,
          monoisotopicMass: 219.21127587021,
          charge: 0,
          mf: 'C16H27',
          atoms: { C: 16, H: 27 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`',
            'dmt@@DiYZVzjjjhR`NDB`b`|pYFIFYVMgzH`NEUCaU@',
            'foA@@@DiYZ^u`mNjjjjjlHHIQr`GB@TDJCr`YCDQcJXsNPKIXkOtP`GBj`xUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh',
            'did@@DiUjfjjj@NDB`b`}PYFIfYV_hb@xUTNET',
            'dkl@@DiUkYijjjjiBhZ`NDB`b`|HYFIfYVMGPN_hb@xUTNET',
          ],
        },
        atomMap: [0],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`',
            'dmt@@DiYZVzjjjhR`NDB`b`|pYFIFYVMgzH`NEUCaU@',
            'foA@@@DiYZ^u`mNjjjjjlHHIQr`GB@TDJCr`YCDQcJXsNPKIXkOtP`GBj`xUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh',
            'did@@DiUjfjjj@NDB`b`}PYFIfYV_hb@xUTNET',
            'dkl@@DiUkYijjjjiBhZ`NDB`b`|HYFIfYVMGPN_hb@xUTNET',
          ],
        },
        atomMap: [2],
        smiles: 'CC1(CCCC2(CCCC3(CCCC1(CC)C23)))',
        mf: 'C17H29',
        idCode: 'fde@B@@KNQJJQJIIJVUm^CFjjjjjj`@@',
        mfInfo: {
          mass: 233.41279211211676,
          monoisotopicMass: 233.22692593467,
          charge: 0,
          mf: 'C17H29',
          atoms: { C: 17, H: 29 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@',
            'foA@@@DjVeYVQeNjjjjjl@hPQP`GB@TDJCt`QCLXSJPsNXKIY~bD@xUTGBj@',
            'fde@@@DjVeYWZQeNlFjjjjjjj@hPQPaQFj@\\HAPPhONADLqaLiCLy`lebhuAlmcl\x7FQB@\\JjCaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@',
            'dct@@DjefVjjj`Ca@hHhOUFIFPVUgzH`NEUCaU@',
            'fde@@@DjefUVYP]Flzjjjjjjj@hQQb`UDb@\\HAPPhOZabHqALicLy`heBlugzHPCaUP\\Jh',
            'flm@@@LddRbbRRbgTGUcNbfjjjjjjjhBaAFJATRHAp`EAB`}FFHcDDrfLsfBbTJsVFrvNsvArN_ha@NEUApj`',
          ],
        },
        atomMap: [0],
        smiles: 'C(CC)CC',
        mf: 'C5H11',
        idCode: 'gGPH@liLmU@@',
        mfInfo: {
          mass: 71.1410277782898,
          monoisotopicMass: 71.08607535453,
          charge: 0,
          mf: 'C5H11',
          atoms: { C: 5, H: 11 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@',
            'foA@@@DjVeYVQeNjjjjjl@hPQP`GB@TDJCt`QCLXSJPsNXKIY~bD@xUTGBj@',
            'fde@@@DjVeYWZQeNlFjjjjjjj@hPQPaQFj@\\HAPPhONADLqaLiCLy`lebhuAlmcl\x7FQB@\\JjCaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@',
            'dct@@DjefVjjj`Ca@hHhOUFIFPVUgzH`NEUCaU@',
            'fde@@@DjefUVYP]Flzjjjjjjj@hQQb`UDb@\\HAPPhOZabHqALicLy`heBlugzHPCaUP\\Jh',
            'flm@@@LddRbbRRbgTGUcNbfjjjjjjjhBaAFJATRHAp`EAB`}FFHcDDrfLsfBbTJsVFrvNsvArN_ha@NEUApj`',
          ],
        },
        atomMap: [3],
        smiles: 'C1(CCCC2(CCCC3(CCCC1C23)))',
        mf: 'C14H23',
        idCode: 'foQ@B@@KNQQQJIIP|UHugUUUUUT@@',
        mfInfo: {
          mass: 191.33293989757635,
          monoisotopicMass: 191.17997574129,
          charge: 0,
          mf: 'C14H23',
          atoms: { C: 14, H: 23 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@',
            'foA@@@DjVeYVQeNjjjjjl@hPQP`GB@TDJCt`QCLXSJPsNXKIY~bD@xUTGBj@',
            'fde@@@DjVeYWZQeNlFjjjjjjj@hPQPaQFj@\\HAPPhONADLqaLiCLy`lebhuAlmcl\x7FQB@\\JjCaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'dax@@DiZZjh@xPJBJCvAdYf_hb@xUTNET',
            'dkl@@DiZVYxZjjjiDhJ`NDB`b`}pYFYaQTMgY~bHCaUPxUP',
            'fde@@@LdRdRbbJbgAFCYuUUUUUUTQPRbeBjMD@xPB`aP^LCHYcBQRFYsAYKEQjCY~bD@xUTGBj@',
          ],
        },
        atomMap: [0],
        smiles: 'C(CC)C',
        mf: 'C4H9',
        idCode: 'gJPH@liLuP@',
        mfInfo: {
          mass: 57.114410373442986,
          monoisotopicMass: 57.07042529007,
          charge: 0,
          mf: 'C4H9',
          atoms: { C: 4, H: 9 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@',
            'foA@@@DjVeYVQeNjjjjjl@hPQP`GB@TDJCt`QCLXSJPsNXKIY~bD@xUTGBj@',
            'fde@@@DjVeYWZQeNlFjjjjjjj@hPQPaQFj@\\HAPPhONADLqaLiCLy`lebhuAlmcl\x7FQB@\\JjCaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'dax@@DiZZjh@xPJBJCvAdYf_hb@xUTNET',
            'dkl@@DiZVYxZjjjiDhJ`NDB`b`}pYFYaQTMgY~bHCaUPxUP',
            'fde@@@LdRdRbbJbgAFCYuUUUUUUTQPRbeBjMD@xPB`aP^LCHYcBQRFYsAYKEQjCY~bD@xUTGBj@',
          ],
        },
        atomMap: [3],
        smiles: 'C1(CCCC2(CCCC3(CCCC1(C)C23)))',
        mf: 'C15H25',
        idCode: 'f`i@B@@KNQQRIQYJDVeV]zjjjjjh@@',
        mfInfo: {
          mass: 205.35955730242316,
          monoisotopicMass: 205.19562580575,
          charge: 0,
          mf: 'C15H25',
          atoms: { C: 15, H: 25 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@',
            'foA@@@DjVeYVQeNjjjjjl@hPQP`GB@TDJCt`QCLXSJPsNXKIY~bD@xUTGBj@',
            'fde@@@DjVeYWZQeNlFjjjjjjj@hPQPaQFj@\\HAPPhONADLqaLiCLy`lebhuAlmcl\x7FQB@\\JjCaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh',
            'did@@DiUjfjjj@NDB`b`}PYFIfYV_hb@xUTNET',
            'dkl@@DiUkYijjjjiBhZ`NDB`b`|HYFIfYVMGPN_hb@xUTNET',
          ],
        },
        atomMap: [0],
        smiles: 'CCC',
        mf: 'C3H7',
        idCode: 'gC`H@liKT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@',
            'foA@@@DjVeYVQeNjjjjjl@hPQP`GB@TDJCt`QCLXSJPsNXKIY~bD@xUTGBj@',
            'fde@@@DjVeYWZQeNlFjjjjjjj@hPQPaQFj@\\HAPPhONADLqaLiCLy`lebhuAlmcl\x7FQB@\\JjCaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh',
            'did@@DiUjfjjj@NDB`b`}PYFIfYV_hb@xUTNET',
            'dkl@@DiUkYijjjjiBhZ`NDB`b`|HYFIfYVMGPN_hb@xUTNET',
          ],
        },
        atomMap: [3],
        smiles: 'C1(CCCC2(CCCC3(CCCC1(CC)C23)))',
        mf: 'C16H27',
        idCode: 'fhy@B@@KNQQRIQIIRbLiw`uUUUUUP@@',
        mfInfo: {
          mass: 219.38617470726996,
          monoisotopicMass: 219.21127587021,
          charge: 0,
          mf: 'C16H27',
          atoms: { C: 16, H: 27 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@',
            'dct@@DjefVjjj`Ca@hHhOUFIFPVUgzH`NEUCaU@',
            'fde@@@DjefUVYP]Flzjjjjjjj@hQQb`UDb@\\HAPPhOZabHqALicLy`heBlugzHPCaUP\\Jh',
            'flm@@@LddRbbRRbgTGUcNbfjjjjjjjhBaAFJATRHAp`EAB`}FFHcDDrfLsfBbTJsVFrvNsvArN_ha@NEUApj`',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh',
            'did@@DiUjfjjj@NDB`b`}PYFIfYV_hb@xUTNET',
            'dkl@@DiUkYijjjjiBhZ`NDB`b`|HYFIfYVMGPN_hb@xUTNET',
          ],
        },
        atomMap: [0],
        smiles: 'CCCC1(CCCC2(CCCC3(CCCC1C23)))',
        mf: 'C17H29',
        idCode: 'fde@B@@KNQIJJIQIJEUc^CFjjjjjj`@@',
        mfInfo: {
          mass: 233.41279211211676,
          monoisotopicMass: 233.22692593467,
          charge: 0,
          mf: 'C17H29',
          atoms: { C: 17, H: 29 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@',
            'dct@@DjefVjjj`Ca@hHhOUFIFPVUgzH`NEUCaU@',
            'fde@@@DjefUVYP]Flzjjjjjjj@hQQb`UDb@\\HAPPhOZabHqALicLy`heBlugzHPCaUP\\Jh',
            'flm@@@LddRbbRRbgTGUcNbfjjjjjjjhBaAFJATRHAp`EAB`}FFHcDDrfLsfBbTJsVFrvNsvArN_ha@NEUApj`',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh',
            'did@@DiUjfjjj@NDB`b`}PYFIfYV_hb@xUTNET',
            'dkl@@DiUkYijjjjiBhZ`NDB`b`|HYFIfYVMGPN_hb@xUTNET',
          ],
        },
        atomMap: [16],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@',
            'foA@@@DjVeYVRcNjjjjjl@hQQR`GB@TDJCt`QCLXSJPsNXKIY~bD@xUTGBj@',
            'fde@@@DjVeYWZRcNlFjjjjjjj@hQQRaUFb@\\HAPPhONADLqaLiCLy`lebhuAlmcl\x7FQB@\\JjCaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`',
            'dmt@@DiYYVzjjjlR`jFHCa@hHhO\\FQbQfEEXt_hb@xUTNET',
            'f`q@@@DiYYV[YrUjjjjjjHb`eCBAD@xPB`aP^TCHXbLXRJXrAQKEY~bD@xUTGBj@',
          ],
        },
        atomMap: [0],
        smiles: 'C3(CCCC1(CCCC2(CCCC(C)C12))(CC3))',
        mf: 'C17H29',
        idCode: 'fde@B@@KNQQIISQJJEgCV}Fjjjjjj`@@',
        mfInfo: {
          mass: 233.41279211211676,
          monoisotopicMass: 233.22692593467,
          charge: 0,
          mf: 'C17H29',
          atoms: { C: 17, H: 29 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@',
            'foA@@@DjVeYVRcNjjjjjl@hQQR`GB@TDJCt`QCLXSJPsNXKIY~bD@xUTGBj@',
            'fde@@@DjVeYWZRcNlFjjjjjjj@hQQRaUFb@\\HAPPhONADLqaLiCLy`lebhuAlmcl\x7FQB@\\JjCaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`',
            'dmt@@DiYYVzjjjlR`jFHCa@hHhO\\FQbQfEEXt_hb@xUTNET',
            'f`q@@@DiYYV[YrUjjjjjjHb`eCBAD@xPB`aP^TCHXbLXRJXrAQKEY~bD@xUTGBj@',
          ],
        },
        atomMap: [4],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@',
            'foA@@@DjVeYVRcNjjjjjl@hQQR`GB@TDJCt`QCLXSJPsNXKIY~bD@xUTGBj@',
            'fde@@@DjVeYWZRcNlFjjjjjjj@hQQRaUFb@\\HAPPhONADLqaLiCLy`lebhuAlmcl\x7FQB@\\JjCaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'diD@@DjVVjjhB`NDB`b`}PQFIFXV_hb@xUTNET',
            'dg|@@DjVUinLYjjjjjpJDhX`NDB`b`|HQFIFXVMGXN_hb@xUTNET',
            'fhy@@@LdbTRTbaRxXTk^jjjjjjj@hQQPaaDj@\\HAPPhOVADLQFLIcHy`leBlualmgzHPCaUP\\Jh',
          ],
        },
        atomMap: [0],
        smiles: 'C3(CCCC1(CCCC2(CCCCC12))(CC3))',
        mf: 'C16H27',
        idCode: 'fhy@B@@KNQQIISQJHlxZw`uUUUUUP@@',
        mfInfo: {
          mass: 219.38617470726996,
          monoisotopicMass: 219.21127587021,
          charge: 0,
          mf: 'C16H27',
          atoms: { C: 16, H: 27 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'ded@@DjVejjj`J@xPJBJCqADYfEgzH`NEUCaU@',
            'foA@@@DjVeYVRcNjjjjjl@hQQR`GB@TDJCt`QCLXSJPsNXKIY~bD@xUTGBj@',
            'fde@@@DjVeYWZRcNlFjjjjjjj@hQQRaUFb@\\HAPPhONADLqaLiCLy`lebhuAlmcl\x7FQB@\\JjCaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'diD@@DjVVjjhB`NDB`b`}PQFIFXV_hb@xUTNET',
            'dg|@@DjVUinLYjjjjjpJDhX`NDB`b`|HQFIFXVMGXN_hb@xUTNET',
            'fhy@@@LdbTRTbaRxXTk^jjjjjjj@hQQPaaDj@\\HAPPhOVADLQFLIcHy`leBlualmgzHPCaUP\\Jh',
          ],
        },
        atomMap: [4],
        smiles: 'CCC',
        mf: 'C3H7',
        idCode: 'gC`H@liKT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`',
            'dcL@@DiYZUnjjjjQJFHCa@hHhOLFQbQfUcQ~bHCaUPxUP',
            'fhi@@@DiYZUUV\\mzjjjjjhbJBTLHyPCa@JBEA{PLabHqeLYGHEdlUfl\x7FQB@\\JjCaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'diD@@DjVVjjhB`NDB`b`}PQFIFXV_hb@xUTNET',
            'dg|@@DjVUinLYjjjjjpJDhX`NDB`b`|HQFIFXVMGXN_hb@xUTNET',
            'fhy@@@LdbTRTbaRxXTk^jjjjjjj@hQQPaaDj@\\HAPPhOVADLQFLIcHy`leBlualmgzHPCaUP\\Jh',
          ],
        },
        atomMap: [0],
        smiles: 'C3(CCC(C)C1(CCCC2(CCCCC12))(CC3))',
        mf: 'C17H29',
        idCode: 'fde@B@@KNQQIIQJKQEgKNCFjjjjjj`@@',
        mfInfo: {
          mass: 233.41279211211676,
          monoisotopicMass: 233.22692593467,
          charge: 0,
          mf: 'C17H29',
          atoms: { C: 17, H: 29 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`',
            'dcL@@DiYZUnjjjjQJFHCa@hHhOLFQbQfUcQ~bHCaUPxUP',
            'fhi@@@DiYZUUV\\mzjjjjjhbJBTLHyPCa@JBEA{PLabHqeLYGHEdlUfl\x7FQB@\\JjCaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'diD@@DjVVjjhB`NDB`b`}PQFIFXV_hb@xUTNET',
            'dg|@@DjVUinLYjjjjjpJDhX`NDB`b`|HQFIFXVMGXN_hb@xUTNET',
            'fhy@@@LdbTRTbaRxXTk^jjjjjjj@hQQPaaDj@\\HAPPhOVADLQFLIcHy`leBlualmgzHPCaUP\\Jh',
          ],
        },
        atomMap: [5],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dk\\@@DjVUfh^vjjjjlBaJFHCa@hHhOBDQbQfEcQvCgzH`NEUCaU@',
            'fhy@@@LdbTRTTLRhKakAjjjjjjj@hQQPaeDb@\\HAPPhOFADLQFLIcHy`leBlual\x7FQB@\\JjCaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'daD@@DiZRzjj`Ca@hHhOXFQfY~bHCaUPxUP',
            'dkl@@DiZUeKjjjjkDhHcj@xPJBJCwAdYfEEPv]GzH`NEUCaU@',
            'flm@@@DiZVUUeirwgQBfjjjjjjjhb`eEJNDJHAp`EAB`|XFPsFDbdLsdBrVJcVFs}DHApjhNET',
          ],
        },
        atomMap: [0],
        smiles: 'C2(CCC1(CCCC3(CCCCC3(C1(C)CC2))))',
        mf: 'C17H29',
        idCode: 'fde@B@@KNQQIIQJYQEgKNCFjjjjjj`@@',
        mfInfo: {
          mass: 233.41279211211676,
          monoisotopicMass: 233.22692593467,
          charge: 0,
          mf: 'C17H29',
          atoms: { C: 17, H: 29 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dk\\@@DjVUfh^vjjjjlBaJFHCa@hHhOBDQbQfEcQvCgzH`NEUCaU@',
            'fhy@@@LdbTRTTLRhKakAjjjjjjj@hQQPaeDb@\\HAPPhOFADLQFLIcHy`leBlual\x7FQB@\\JjCaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'daD@@DiZRzjj`Ca@hHhOXFQfY~bHCaUPxUP',
            'dkl@@DiZUeKjjjjkDhHcj@xPJBJCwAdYfEEPv]GzH`NEUCaU@',
            'flm@@@DiZVUUeirwgQBfjjjjjjjhb`eEJNDJHAp`EAB`|XFPsFDbdLsdBrVJcVFs}DHApjhNET',
          ],
        },
        atomMap: [12],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dk\\@@DjVUfh^vjjjjlBaJFHCa@hHhOBDQbQfEcQvCgzH`NEUCaU@',
            'fhy@@@LdbTRTTLRhKakAjjjjjjj@hQQPaeDb@\\HAPPhOFADLQFLIcHy`leBlual\x7FQB@\\JjCaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@',
            'dcL@@DjefUmjjjjPJDHCa@hHhOUFIFPVUgzH`NEUCaU@',
            'fde@@@DjefUVVVcNmFjjjjjjj@hQQ``QDj@\\HAPPhOZabHqALicLy`heBlugzHPCaUP\\Jh',
            'flm@@@LddRbbRRbSehskQBfjjjjjjjhBaEFBADRhAp`EAB`}FFHcDDrfLsfBbTJsVFrvNsvArN_ha@NEUApj`',
          ],
        },
        atomMap: [0],
        smiles: 'C2(CCC1(CCCC3(CCCCC3(C1CC2))))',
        mf: 'C16H27',
        idCode: 'fhy@B@@KNQQIIIQJHlxZw`uUUUUUP@@',
        mfInfo: {
          mass: 219.38617470726996,
          monoisotopicMass: 219.21127587021,
          charge: 0,
          mf: 'C16H27',
          atoms: { C: 16, H: 27 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dk\\@@DjVUfh^vjjjjlBaJFHCa@hHhOBDQbQfEcQvCgzH`NEUCaU@',
            'fhy@@@LdbTRTTLRhKakAjjjjjjj@hQQPaeDb@\\HAPPhOFADLQFLIcHy`leBlual\x7FQB@\\JjCaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@',
            'dcL@@DjefUmjjjjPJDHCa@hHhOUFIFPVUgzH`NEUCaU@',
            'fde@@@DjefUVVVcNmFjjjjjjj@hQQ``QDj@\\HAPPhOZabHqALicLy`heBlugzHPCaUP\\Jh',
            'flm@@@LddRbbRRbSehskQBfjjjjjjjhBaEFBADRhAp`EAB`}FFHcDDrfLsfBbTJsVFrvNsvArN_ha@NEUApj`',
          ],
        },
        atomMap: [12],
        smiles: 'CCC',
        mf: 'C3H7',
        idCode: 'gC`H@liKT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'dmt@@DiYUbZjjjdR`j@xPJBJCsAdXdYaQV_hb@xUTNET',
            'f`q@@@DiYUfyHpVjjjjjjHb`eCJND@xPB`aP^TCHXbLXRJYrAYJEY~bD@xUTGBj@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@',
            'dcL@@DjefUmjjjjPJDHCa@hHhOUFIFPVUgzH`NEUCaU@',
            'fde@@@DjefUVVVcNmFjjjjjjj@hQQ``QDj@\\HAPPhOZabHqALicLy`heBlugzHPCaUP\\Jh',
            'flm@@@LddRbbRRbSehskQBfjjjjjjjhBaEFBADRhAp`EAB`}FFHcDDrfLsfBbTJsVFrvNsvArN_ha@NEUApj`',
          ],
        },
        atomMap: [0],
        smiles: 'C2(CCC1(CCCC3(CCCC(C)C3(C1CC2))))',
        mf: 'C17H29',
        idCode: 'fde@B@@KNQQIIIQJJEgCV}Fjjjjjj`@@',
        mfInfo: {
          mass: 233.41279211211676,
          monoisotopicMass: 233.22692593467,
          charge: 0,
          mf: 'C17H29',
          atoms: { C: 17, H: 29 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'dmt@@DiYUbZjjjdR`j@xPJBJCsAdXdYaQV_hb@xUTNET',
            'f`q@@@DiYUfyHpVjjjjjjHb`eCJND@xPB`aP^TCHXbLXRJYrAYJEY~bD@xUTGBj@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gGP@Djfj`NDJBTGiL\x7FQHGBjcaU@',
            'dcL@@DjefUmjjjjPJDHCa@hHhOUFIFPVUgzH`NEUCaU@',
            'fde@@@DjefUVVVcNmFjjjjjjj@hQQ``QDj@\\HAPPhOZabHqALicLy`heBlugzHPCaUP\\Jh',
            'flm@@@LddRbbRRbSehskQBfjjjjjjjhBaEFBADRhAp`EAB`}FFHcDDrfLsfBbTJsVFrvNsvArN_ha@NEUApj`',
          ],
        },
        atomMap: [13],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dg|@@DjVUiVF[jjjjjpJDHZ`NDB`b`|HQFIFXVMGXN_hb@xUTNET',
            'fhy@@@DjVUi]VBeXwjjjjjjj`JDDThYQH`GB@TDJCu`QCDQcBXrNXKIPkMX[KY~bD@xUTGBj@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'deT@@DiYUIjjjkDhJab@xPJBJCwAdXdYaQVMGzH`NEUCaU@',
            'dg|@@DiYUZrXUjjjjjqJBhX`NDB`b`}HYFIFXTUcPNSgzH`NEUCaU@',
          ],
        },
        atomMap: [0],
        smiles: 'C3(CCC2(CCCCC1(C2(CCCC1(C))CC3)))',
        mf: 'C17H29',
        idCode: 'fde@B@@KJSJkKJrseoNcUUUUUUP@@',
        mfInfo: {
          mass: 233.41279211211676,
          monoisotopicMass: 233.22692593467,
          charge: 0,
          mf: 'C17H29',
          atoms: { C: 17, H: 29 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dg|@@DjVUiVF[jjjjjpJDHZ`NDB`b`|HQFIFXVMGXN_hb@xUTNET',
            'fhy@@@DjVUi]VBeXwjjjjjjj`JDDThYQH`GB@TDJCu`QCDQcBXrNXKIPkMX[KY~bD@xUTGBj@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'deT@@DiYUIjjjkDhJab@xPJBJCwAdXdYaQVMGzH`NEUCaU@',
            'dg|@@DiYUZrXUjjjjjqJBhX`NDB`b`}HYFIFXTUcPNSgzH`NEUCaU@',
          ],
        },
        atomMap: [8],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dg|@@DjVUiVF[jjjjjpJDHZ`NDB`b`|HQFIFXVMGXN_hb@xUTNET',
            'fhy@@@DjVUi]VBeXwjjjjjjj`JDDThYQH`GB@TDJCu`QCDQcBXrNXKIPkMX[KY~bD@xUTGBj@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dk\\@@DjVUiX^fjjjjlBaBFhCa@hHhOBDQbQfEcQvCgzH`NEUCaU@',
            'fhy@@@LdbTRTbLrXKbkAjjjjjjj@hPQPaeDj@\\HAPPhOFADLQFLIcHy`leBlual\x7FQB@\\JjCaU@',
          ],
        },
        atomMap: [0],
        smiles: 'C3(CCC2(CCCCC1(C2(CCCC1)CC3)))',
        mf: 'C16H27',
        idCode: 'fhy@B@@KJSJkKJkNVB{uUUUUUT@@',
        mfInfo: {
          mass: 219.38617470726996,
          monoisotopicMass: 219.21127587021,
          charge: 0,
          mf: 'C16H27',
          atoms: { C: 16, H: 27 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dg|@@DjVUiVF[jjjjjpJDHZ`NDB`b`|HQFIFXVMGXN_hb@xUTNET',
            'fhy@@@DjVUi]VBeXwjjjjjjj`JDDThYQH`GB@TDJCu`QCDQcBXrNXKIPkMX[KY~bD@xUTGBj@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dk\\@@DjVUiX^fjjjjlBaBFhCa@hHhOBDQbQfEcQvCgzH`NEUCaU@',
            'fhy@@@LdbTRTbLrXKbkAjjjjjjj@hPQPaeDj@\\HAPPhOFADLQFLIcHy`leBlual\x7FQB@\\JjCaU@',
          ],
        },
        atomMap: [8],
        smiles: 'CCC',
        mf: 'C3H7',
        idCode: 'gC`H@liKT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'deT@@DiYUIjjjkDhJab@xPJBJCwAdXdYaQVMGzH`NEUCaU@',
            'foQ@@@DiYUZTcEVtzjjjjjbHhIPpce@ND@hHTGi@rFHcFDbfL`VRs}DHApjhNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dk\\@@DjVUiX^fjjjjlBaBFhCa@hHhOBDQbQfEcQvCgzH`NEUCaU@',
            'fhy@@@LdbTRTbLrXKbkAjjjjjjj@hPQPaeDj@\\HAPPhOFADLQFLIcHy`leBlual\x7FQB@\\JjCaU@',
          ],
        },
        atomMap: [0],
        smiles: 'C3(CCC2(CCCC(C)C1(C2(CCCC1)CC3)))',
        mf: 'C17H29',
        idCode: 'fde@B@@KJSJkKJrsehn}UUUUUUP@@',
        mfInfo: {
          mass: 233.41279211211676,
          monoisotopicMass: 233.22692593467,
          charge: 0,
          mf: 'C17H29',
          atoms: { C: 17, H: 29 },
          unsaturation: 3.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'gOp@DiYKjjhjApaPR`|QdqQl\x7FQHGBjcaU@',
            'deT@@DiYUIjjjkDhJab@xPJBJCwAdXdYaQVMGzH`NEUCaU@',
            'foQ@@@DiYUZTcEVtzjjjjjbHhIPpce@ND@hHTGi@rFHcFDbfL`VRs}DHApjhNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjVVajjjPJDhCa@hHhOTDQbQfEgzH`NEUCaU@',
            'dk\\@@DjVUiX^fjjjjlBaBFhCa@hHhOBDQbQfEcQvCgzH`NEUCaU@',
            'fhy@@@LdbTRTbLrXKbkAjjjjjjj@hPQPaeDj@\\HAPPhOFADLQFLIcHy`leBlual\x7FQB@\\JjCaU@',
          ],
        },
        atomMap: [9],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
    ]);
  });
});
