import OCL from 'openchemlib';

import { fragment } from '../../fragment.js';

const { Molecule } = OCL;

describe('fragment', () => {
  it('CCCCC2CCC1C(CC)CC(=O)CC1C2', () => {
    const molecule = Molecule.fromSmiles('CCCCC2CCC1C(CC)CC(=O)CC1C2'); //3 cyclohexane connected
    const result = fragment(molecule);
    expect(result).toStrictEqual([
      {
        mf: 'C16H28O',
        idCode: 'fhiA@@@YEDeDddbeQbcMUUUUU@@@',
        mfInfo: {
          mass: 236.393520385644,
          monoisotopicMass: 236.21401552201002,
          charge: 0,
          mf: 'C16H28O',
          atoms: { C: 16, H: 28, O: 1 },
          unsaturation: 3,
        },
        fragmentType: 'Molecular Ion',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'eM@HzCaJBhOIewzJCaUSaU@',
          'gC`@Dkj@xPhIP^pr\\l\x7FQHGBjcaU@',
          'gJP@DkZhCaB`eAxcIrsY~bPNEUGBj@',
          'gNp@DkVjj@xPhIP^hr\\lvFOtRApjhxUP',
        ],
        atomMap: [0],
        smiles: 'C',
        mf: 'CH3',
        idCode: 'eFBAYc@@',
        mfInfo: {
          mass: 15.03455815890258,
          monoisotopicMass: 15.02347509669,
          charge: 0,
          mf: 'CH3',
          atoms: { C: 1, H: 3 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'eM@HzCaJBhOIewzJCaUSaU@',
          'gC`@Dkj@xPhIP^pr\\l\x7FQHGBjcaU@',
          'gJP@DkZhCaB`eAxcIrsY~bPNEUGBj@',
          'gNp@DkVjj@xPhIP^hr\\lvFOtRApjhxUP',
        ],
        atomMap: [1],
        smiles: 'CCCC2(CCC1(C(CC)CC(=O)CC1C2))',
        mf: 'C15H25O',
        idCode: 'fhiAB@O@VTeVUmYqRMZjjjjfh@@',
        mfInfo: {
          mass: 221.35896222674143,
          monoisotopicMass: 221.19054042532002,
          charge: 0,
          mf: 'C15H25O',
          atoms: { C: 15, H: 25, O: 1 },
          unsaturation: 3.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
          'gJP@DiZhCaB`eAxcIbs]~bPNEUGBj@',
          'gNp@Di^jj@xPhIP^hrXlwFOtRApjhxUP',
          'diD@@Di^Vjj`Ca@hHhO\\FQbYgEEXv_hb@xUTNET',
        ],
        atomMap: [0],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
          'gJP@DiZhCaB`eAxcIbs]~bPNEUGBj@',
          'gNp@Di^jj@xPhIP^hrXlwFOtRApjhxUP',
          'diD@@Di^Vjj`Ca@hHhO\\FQbYgEEXv_hb@xUTNET',
        ],
        atomMap: [2],
        smiles: 'CCC2(CCC1(C(CC)CC(=O)CC1C2))',
        mf: 'C14H23O',
        idCode: 'f`qAB@G@VTeYVugxKQjjjjij@@',
        mfInfo: {
          mass: 207.33234482189462,
          monoisotopicMass: 207.17489036086002,
          charge: 0,
          mf: 'C14H23O',
          atoms: { C: 14, H: 23, O: 1 },
          unsaturation: 3.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
          'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`',
          'diD@@DiYVjj`Ca@hHhO\\FQbQfEeXw_hb@xUTNET',
          'dmt@@DiYWafjjjdRcb@xPJBJCtadXdYaYVMwPN_hb@xUTNET',
        ],
        atomMap: [0],
        smiles: 'CCC',
        mf: 'C3H7',
        idCode: 'gC`H@liKT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
          'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`',
          'diD@@DiYVjj`Ca@hHhO\\FQbQfEeXw_hb@xUTNET',
          'dmt@@DiYWafjjjdRcb@xPJBJCtadXdYaYVMwPN_hb@xUTNET',
        ],
        atomMap: [3],
        smiles: 'CC2(CCC1(C(CC)CC(=O)CC1C2))',
        mf: 'C13H21O',
        idCode: 'foAAB@K@VTee[V]gEZjjjjZ`@@',
        mfInfo: {
          mass: 193.30572741704782,
          monoisotopicMass: 193.15924029640001,
          charge: 0,
          mf: 'C13H21O',
          atoms: { C: 13, H: 21, O: 1 },
          unsaturation: 3.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
          'dax@@DjUZjh@xPJBJCuADXfYaY~bHCaUPxUP',
          'dmt@@DjUVvFjjjdBbb@xPJBJCpaDXfYaYTMgY~bHCaUPxUP',
          'dkl@@DjUVuXZjjjk@hh`R@xPJBJCvaDXfYaYTMgXLSb}~bHCaUPxUP',
        ],
        atomMap: [0],
        smiles: 'CCCC',
        mf: 'C4H9',
        idCode: 'gJPH@liJuP@',
        mfInfo: {
          mass: 57.114410373442986,
          monoisotopicMass: 57.07042529007,
          charge: 0,
          mf: 'C4H9',
          atoms: { C: 4, H: 9 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
          'dax@@DjUZjh@xPJBJCuADXfYaY~bHCaUPxUP',
          'dmt@@DjUVvFjjjdBbb@xPJBJCpaDXfYaYTMgY~bHCaUPxUP',
          'dkl@@DjUVuXZjjjk@hh`R@xPJBJCvaDXfYaYTMgXLSb}~bHCaUPxUP',
        ],
        atomMap: [4],
        smiles: 'C2(CCC1(C(CC)CC(=O)CC1C2))',
        mf: 'C12H19O',
        idCode: 'dg|H`CAYRYVugiiVjjjfh@@',
        mfInfo: {
          mass: 179.27911001220102,
          monoisotopicMass: 179.14359023194,
          charge: 0,
          mf: 'C12H19O',
          atoms: { C: 12, H: 19, O: 1 },
          unsaturation: 3.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
          'dax@@DjVZjj@hCa@hHhOTDQbQfEwzH`NEUCaU@',
          'dcLH@@rJIJIHusUUUVEQUGDApaTCTGnSBbh[Nb^WOtQB\\JigBj@',
          'dk\\H@@RYVU^ntvjjjjpjJhx`NDJ`Z`|jYfEEPv]@yOKay~bHSaULxUP',
        ],
        atomMap: [0],
        smiles: 'CCCCC2(CCC1(CCC(=O)CC1C2))',
        mf: 'C14H23O',
        idCode: 'f`qAB@O@VTeUe[UdjsjjjjjZ@@',
        mfInfo: {
          mass: 207.33234482189462,
          monoisotopicMass: 207.17489036086002,
          charge: 0,
          mf: 'C14H23O',
          atoms: { C: 14, H: 23, O: 1 },
          unsaturation: 3.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
          'dax@@DjVZjj@hCa@hHhOTDQbQfEwzH`NEUCaU@',
          'dcLH@@rJIJIHusUUUVEQUGDApaTCTGnSBbh[Nb^WOtQB\\JigBj@',
          'dk\\H@@RYVU^ntvjjjjpjJhx`NDJ`Z`|jYfEEPv]@yOKay~bHSaULxUP',
        ],
        atomMap: [9],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'eM@HzCaJBhOIewzJCaUSaU@',
          'gJP@DkjhCaB`eA{CIrc}D`\\JjNET',
          'dax@@DkfZjjDhCa@hHhOTFQrQdEgzH`NEUCaU@',
          'dcLH@@rJIJIHusUUUVEQUGDApcTDtGnSBbh[Nb^WOtQF\\JjWBj@',
        ],
        atomMap: [0],
        smiles: 'CCCCC2(CCC1(C(C)CC(=O)CC1C2))',
        mf: 'C15H25O',
        idCode: 'fhiAB@@`VTeUe[VYJlzjjjjih@@',
        mfInfo: {
          mass: 221.35896222674143,
          monoisotopicMass: 221.19054042532002,
          charge: 0,
          mf: 'C15H25O',
          atoms: { C: 15, H: 25, O: 1 },
          unsaturation: 3.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'eM@HzCaJBhOIewzJCaUSaU@',
          'gJP@DkjhCaB`eA{CIrc}D`\\JjNET',
          'dax@@DkfZjjDhCa@hHhOTFQrQdEgzH`NEUCaU@',
          'dcLH@@rJIJIHusUUUVEQUGDApcTDtGnSBbh[Nb^WOtQF\\JjWBj@',
        ],
        atomMap: [10],
        smiles: 'C',
        mf: 'CH3',
        idCode: 'eFBAYc@@',
        mfInfo: {
          mass: 15.03455815890258,
          monoisotopicMass: 15.02347509669,
          charge: 0,
          mf: 'CH3',
          atoms: { C: 1, H: 3 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gGP@DjZj`NDJBTGdHd_hdCaUQpj`',
            'dmt@@DjYeVfjjjlBbBDhCa@hHhOLDQBQfEeY~bHCaUPxUP',
            'dk\\H@@RYVUVftvjjjjpjJHZ`NDJ`Z`|jYfEEPt]`yNKqy~bHSaULxUP',
            'dg|H@@RYVUWimMjjjjhbhhajMHCaBhFhOZfYaQTMGXNSb}lGgzHaNETsaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJQ@@dru@\\JTBhOQY~bRNETgBj@',
            'daDH@@RYVifjj`j@xRJAJCvIfXT_hbPxURNET',
            'dmtH@@RYVUifjjjpjJHZ`NDb`R`|rYfEEPt]gzHdNETcaU@',
            'dk\\H@@RYVUVftvjjjjpbJhX`NDb`R`}JYfEEPt]`yNKwzHdNETcaU@',
          ],
        },
        atomMap: [0],
        smiles: 'CCCCC1(CCCC(CC=O)C1)',
        mf: 'C12H22O',
        idCode: 'dklH@@rIJIJEKaZjjj`@',
        mfInfo: {
          mass: 182.30293227436835,
          monoisotopicMass: 182.16706532863,
          charge: 0,
          mf: 'C12H22O',
          atoms: { C: 12, H: 22, O: 1 },
          unsaturation: 2,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gGP@DjZj`NDJBTGdHd_hdCaUQpj`',
            'dmt@@DjYeVfjjjlBbBDhCa@hHhOLDQBQfEeY~bHCaUPxUP',
            'dk\\H@@RYVUVftvjjjjpjJHZ`NDJ`Z`|jYfEEPt]`yNKqy~bHSaULxUP',
            'dg|H@@RYVUWimMjjjjhbhhajMHCaBhFhOZfYaQTMGXNSb}lGgzHaNETsaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJQ@@dru@\\JTBhOQY~bRNETgBj@',
            'daDH@@RYVifjj`j@xRJAJCvIfXT_hbPxURNET',
            'dmtH@@RYVUifjjjpjJHZ`NDb`R`|rYfEEPt]gzHdNETcaU@',
            'dk\\H@@RYVUVftvjjjjpbJhX`NDb`R`}JYfEEPt]`yNKwzHdNETcaU@',
          ],
        },
        atomMap: [8],
        smiles: 'C(CC)C',
        mf: 'C4H9',
        idCode: 'gJPH@liLuP@',
        mfInfo: {
          mass: 57.114410373442986,
          monoisotopicMass: 57.07042529007,
          charge: 0,
          mf: 'C4H9',
          atoms: { C: 4, H: 9 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gGP@DjZj`NDJBTGdHd_hdCaUQpj`',
            'dmt@@DjYeVfjjjlBbBDhCa@hHhOLDQBQfEeY~bHCaUPxUP',
            'dk\\H@@RYVUVftvjjjjpjJHZ`NDJ`Z`|jYfEEPt]`yNKqy~bHSaULxUP',
            'dg|H@@RYVUWimMjjjjhbhhajMHCaBhFhOZfYaQTMGXNSb}lGgzHaNETsaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJQ@@dru@\\JTBhOQY~bRNETgBj@',
            'daDH@@RYVifjj`j@xRJAJCvIfXT_hbPxURNET',
            'dmtH@@RYVUifjjjpjJHZ`NDb`R`|rYfEEPt]gzHdNETcaU@',
            'dg|H@@RYVUUieMjjjjhbhhajEhCaHhDhORfYaQTMGXNSbq~bICaUHxUP',
          ],
        },
        atomMap: [0],
        smiles: 'CCCCC1(CCCC(C)C1)',
        mf: 'C11H22',
        idCode: 'dmt@@LdbRTqkjjjj@@',
        mfInfo: {
          mass: 154.29279145331483,
          monoisotopicMass: 154.17215070906,
          charge: 0,
          mf: 'C11H22',
          atoms: { C: 11, H: 22 },
          unsaturation: 1,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gGP@DjZj`NDJBTGdHd_hdCaUQpj`',
            'dmt@@DjYeVfjjjlBbBDhCa@hHhOLDQBQfEeY~bHCaUPxUP',
            'dk\\H@@RYVUVftvjjjjpjJHZ`NDJ`Z`|jYfEEPt]`yNKqy~bHSaULxUP',
            'dg|H@@RYVUWimMjjjjhbhhajMHCaBhFhOZfYaQTMGXNSb}lGgzHaNETsaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJQ@@dru@\\JTBhOQY~bRNETgBj@',
            'daDH@@RYVifjj`j@xRJAJCvIfXT_hbPxURNET',
            'dmtH@@RYVUifjjjpjJHZ`NDb`R`|rYfEEPt]gzHdNETcaU@',
            'dg|H@@RYVUUieMjjjjhbhhajEhCaHhDhORfYaQTMGXNSbq~bICaUHxUP',
          ],
        },
        atomMap: [8],
        smiles: 'C(CC)CC=O',
        mf: 'C5H9O',
        idCode: 'gNqHFEeIeZjP@',
        mfInfo: {
          mass: 85.12455119449652,
          monoisotopicMass: 85.06533990964,
          charge: 0,
          mf: 'C5H9O',
          atoms: { C: 5, H: 9, O: 1 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gGP@DjZj`NDJBTGdHd_hdCaUQpj`',
            'dmt@@DjYeVfjjjlBbBDhCa@hHhOLDQBQfEeY~bHCaUPxUP',
            'dk\\H@@RYVUVftvjjjjpjJHZ`NDJ`Z`|jYfEEPt]`yNKqy~bHSaULxUP',
            'dg|H@@RYVUWimMjjjjhbhhajMHCaBhFhOZfYaQTMGXNSb}lGgzHaNETsaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'deTH@@RYVvfZjjdJaj@xQJ@jCqIaPt]gzHbNETSaU@',
            'dk\\H@@RYVUvfWVjjjjHjJHZaZ@xQJ@jCpifXTUCQvSbq~bHcaUDxUP',
            'foAA@@@YEDeDddcQbcMUUUUQBTTHYPj`GBDTAJCvdYcBQRFQsAYKEP[KY~bDPxUQGBj@',
          ],
        },
        atomMap: [0],
        smiles: 'CCCCC1(CCCCC1)',
        mf: 'C10H20',
        idCode: 'deT@@DjU_kjjjh@@',
        mfInfo: {
          mass: 140.26617404846803,
          monoisotopicMass: 140.1565006446,
          charge: 0,
          mf: 'C10H20',
          atoms: { C: 10, H: 20 },
          unsaturation: 1,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gGP@DjZj`NDJBTGdHd_hdCaUQpj`',
            'dmt@@DjYeVfjjjlBbBDhCa@hHhOLDQBQfEeY~bHCaUPxUP',
            'dk\\H@@RYVUVftvjjjjpjJHZ`NDJ`Z`|jYfEEPt]`yNKqy~bHSaULxUP',
            'dg|H@@RYVUWimMjjjjhbhhajMHCaBhFhOZfYaQTMGXNSb}lGgzHaNETsaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'deTH@@RYVvfZjjdJaj@xQJ@jCqIaPt]gzHbNETSaU@',
            'dk\\H@@RYVUvfWVjjjjHjJHZaZ@xQJ@jCpifXTUCQvSbq~bHcaUDxUP',
            'foAA@@@YEDeDddcQbcMUUUUQBTTHYPj`GBDTAJCvdYcBQRFQsAYKEP[KY~bDPxUQGBj@',
          ],
        },
        atomMap: [8],
        smiles: 'C(CC)CC(=O)C',
        mf: 'C6H11O',
        idCode: 'daxH`FAYRYVji`@',
        mfInfo: {
          mass: 99.15116859934332,
          monoisotopicMass: 99.08098997409999,
          charge: 0,
          mf: 'C6H11O',
          atoms: { C: 6, H: 11, O: 1 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'deTH@@RYVvfZjjdJaj@xQJ@jCqIaPt]gzHbNETSaU@',
            'dcLH@@RYVUzYjjjkBhhaj@xQJ@jCpifXTUCQvSb}~bHcaUDxUP',
            'dk\\H@@RYVUVftvjjjjpjJHZ`NDR`J`|jYfEEPt]`yNKqy~bHcaUDxUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJQ@@dru@\\JTBhOQY~bRNETgBj@',
            'daDH@@RYVifjj`j@xRJAJCvIfXT_hbPxURNET',
            'dmtH@@RYVUifjjjpjJHZ`NDb`R`|rYfEEPt]gzHdNETcaU@',
            'dg|H@@RYVUUieMjjjjhbhhajEhCaHhDhORfYaQTMGXNSbq~bICaUHxUP',
          ],
        },
        atomMap: [0],
        smiles: 'CCCCC1(CCC(CCC)C(C)C1)',
        mf: 'C14H28',
        idCode: 'dg\\@@LdbbRJrSCUUUUP@@',
        mfInfo: {
          mass: 196.37264366785524,
          monoisotopicMass: 196.21910090244,
          charge: 0,
          mf: 'C14H28',
          atoms: { C: 14, H: 28 },
          unsaturation: 1,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'deTH@@RYVvfZjjdJaj@xQJ@jCqIaPt]gzHbNETSaU@',
            'dcLH@@RYVUzYjjjkBhhaj@xQJ@jCpifXTUCQvSb}~bHcaUDxUP',
            'dk\\H@@RYVUVftvjjjjpjJHZ`NDR`J`|jYfEEPt]`yNKqy~bHcaUDxUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJQ@@dru@\\JTBhOQY~bRNETgBj@',
            'daDH@@RYVifjj`j@xRJAJCvIfXT_hbPxURNET',
            'dmtH@@RYVUifjjjpjJHZ`NDb`R`|rYfEEPt]gzHdNETcaU@',
            'dg|H@@RYVUUieMjjjjhbhhajEhCaHhDhORfYaQTMGXNSbq~bICaUHxUP',
          ],
        },
        atomMap: [11],
        smiles: 'CC=O',
        mf: 'C2H3O',
        idCode: 'gCaHLEeIZP@',
        mfInfo: {
          mass: 43.04469897995611,
          monoisotopicMass: 43.01838971626,
          charge: 0,
          mf: 'C2H3O',
          atoms: { C: 2, H: 3, O: 1 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'deTH@@RYVvfZjjdJaj@xQJ@jCqIaPt]gzHbNETSaU@',
            'dcLH@@RYVUzYjjjkBhhaj@xQJ@jCpifXTUCQvSb}~bHcaUDxUP',
            'dk\\H@@RYVUVftvjjjjpjJHZ`NDR`J`|jYfEEPt]`yNKqy~bHcaUDxUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'deTH@@RYVvfZjjdJaj@xQJ@jCqIaPt]gzHbNETSaU@',
            'dk\\H@@RYVUvfWVjjjjHjJHZaZ@xQJ@jCpifXTUCQvSbq~bHcaUDxUP',
            'foAA@@@YEDeDddcQbcMUUUUQBTTHYPj`GBDTAJCvdYcBQRFQsAYKEP[KY~bDPxUQGBj@',
          ],
        },
        atomMap: [0],
        smiles: 'CCCCC1(CCC(CCC)CC1)',
        mf: 'C13H26',
        idCode: 'dkl@@DjU]Wkjjjjh@@',
        mfInfo: {
          mass: 182.3460262630084,
          monoisotopicMass: 182.20345083798,
          charge: 0,
          mf: 'C13H26',
          atoms: { C: 13, H: 26 },
          unsaturation: 1,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'deTH@@RYVvfZjjdJaj@xQJ@jCqIaPt]gzHbNETSaU@',
            'dcLH@@RYVUzYjjjkBhhaj@xQJ@jCpifXTUCQvSb}~bHcaUDxUP',
            'dk\\H@@RYVUVftvjjjjpjJHZ`NDR`J`|jYfEEPt]`yNKqy~bHcaUDxUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'deTH@@RYVvfZjjdJaj@xQJ@jCqIaPt]gzHbNETSaU@',
            'dk\\H@@RYVUvfWVjjjjHjJHZaZ@xQJ@jCpifXTUCQvSbq~bHcaUDxUP',
            'foAA@@@YEDeDddcQbcMUUUUQBTTHYPj`GBDTAJCvdYcBQRFQsAYKEP[KY~bDPxUQGBj@',
          ],
        },
        atomMap: [11],
        smiles: 'CC(=O)C',
        mf: 'C3H5O',
        idCode: 'gJQHLEeIZf@@',
        mfInfo: {
          mass: 57.071316384802905,
          monoisotopicMass: 57.03403978071999,
          charge: 0,
          mf: 'C3H5O',
          atoms: { C: 3, H: 5, O: 1 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJQ@@dru@\\JTBhOQY~bRNETgBj@',
            'daDH@@RYVifjj`j@xRJAJCvIfXT_hbPxURNET',
            'dmtH@@RYVUifjjjpjJHZ`NDb`R`|rYfEEPt]gzHdNETcaU@',
            'dk\\H@@RYVUVftvjjjjpbJhX`NDb`R`}JYfEEPt]`yNKwzHdNETcaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'deTH@@RYVvfZjjdJaj@xQJ@jCqIaPt]gzHbNETSaU@',
            'dk\\H@@RYVUvfWVjjjjHjJHZaZ@xQJ@jCpifXTUCQvSbq~bHcaUDxUP',
            'foAA@@@YEDeDddcQbcMUUUUQBTTHYPj`GBDTAJCvdYcBQRFQsAYKEP[KY~bDPxUQGBj@',
          ],
        },
        atomMap: [0],
        smiles: 'CCCCC1(CCC(C(CC)C)CC1)',
        mf: 'C14H28',
        idCode: 'dg\\@@LdbbRqRWSUUUUP@@',
        mfInfo: {
          mass: 196.37264366785524,
          monoisotopicMass: 196.21910090244,
          charge: 0,
          mf: 'C14H28',
          atoms: { C: 14, H: 28 },
          unsaturation: 1,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJQ@@dru@\\JTBhOQY~bRNETgBj@',
            'daDH@@RYVifjj`j@xRJAJCvIfXT_hbPxURNET',
            'dmtH@@RYVUifjjjpjJHZ`NDb`R`|rYfEEPt]gzHdNETcaU@',
            'dk\\H@@RYVUVftvjjjjpbJhX`NDb`R`}JYfEEPt]`yNKwzHdNETcaU@',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'deTH@@RYVvfZjjdJaj@xQJ@jCqIaPt]gzHbNETSaU@',
            'dk\\H@@RYVUvfWVjjjjHjJHZaZ@xQJ@jCpifXTUCQvSbq~bHcaUDxUP',
            'foAA@@@YEDeDddcQbcMUUUUQBTTHYPj`GBDTAJCvdYcBQRFQsAYKEP[KY~bDPxUQGBj@',
          ],
        },
        atomMap: [12],
        smiles: 'C(=O)C',
        mf: 'C2H3O',
        idCode: 'gCaHDEeIi`@',
        mfInfo: {
          mass: 43.04469897995611,
          monoisotopicMass: 43.01838971626,
          charge: 0,
          mf: 'C2H3O',
          atoms: { C: 2, H: 3, O: 1 },
          unsaturation: 1.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'daD@@DjUZzjjhB`NDB`b`}PQFIfXV_hb@xUTNET',
            'dmt@@DjUUZzjjjlBbjNHCa@hHhOBDQbYfEePv]GzH`NEUCaU@',
            'foA@@@DjUUUZgMVjjjjjb@hiQpaQ@ND@hHTGm@bFHsFDrdLsdBrVJc}DHApjhNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'deT@@DjVYjZjji@hR`NDB`b`}PQFIFPV_hb@xUTNET',
            'dk\\@@DjVY}j^VjjjjbBaJLhd`NDB`b`|hQFIFPVUcYvCdq~bHCaUPxUP',
            'foAA@@@YEDeDddcQbcMUUUUQBTTHYPj`GBFTDjCqdYcBQRFQsAYKEQkcY[OtPcGBjdxUP',
          ],
        },
        atomMap: [0],
        smiles: 'CCCCCCC1(CC(CC(C1)CC)=O)',
        mf: 'C14H26O',
        idCode: 'do|H@@RYV]]ZYjjjjh@@',
        mfInfo: {
          mass: 210.35616708406198,
          monoisotopicMass: 210.19836545755,
          charge: 0,
          mf: 'C14H26O',
          atoms: { C: 14, H: 26, O: 1 },
          unsaturation: 2,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'daD@@DjUZzjjhB`NDB`b`}PQFIfXV_hb@xUTNET',
            'dmt@@DjUUZzjjjlBbjNHCa@hHhOBDQbYfEePv]GzH`NEUCaU@',
            'foA@@@DjUUUZgMVjjjjjb@hiQpaQ@ND@hHTGm@bFHsFDrdLsdBrVJc}DHApjhNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'deT@@DjVYjZjji@hR`NDB`b`}PQFIFPV_hb@xUTNET',
            'dk\\@@DjVY}j^VjjjjbBaJLhd`NDB`b`|hQFIFPVUcYvCdq~bHCaUPxUP',
            'foAA@@@YEDeDddcQbcMUUUUQBTTHYPj`GBFTDjCqdYcBQRFQsAYKEQkcY[OtPcGBjdxUP',
          ],
        },
        atomMap: [5],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'daD@@DjUZzjjhB`NDB`b`}PQFIfXV_hb@xUTNET',
            'dmt@@DjUUZzjjjlBbjNHCa@hHhOBDQbYfEePv]GzH`NEUCaU@',
            'foA@@@DjUUUZgMVjjjjjb@hiQpaQ@ND@hHTGm@bFHsFDrdLsdBrVJc}DHApjhNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'deT@@DjVVhZjjk@hR`b@xPJBJCuADXdYaQ~bHCaUPxUP',
            'dg|H@@rJIJIKPurzuUUUTQTUQqDdApaTCTGiSBbh[NbXWMp|\x7FQDIpjf\\Jh',
            'f`qA@@@YEDeDdeJj\\TYjjjjjbDhiQpbQ@NDDhFTGcHsFDbdLsdBrTJpvVqv_haBNETqpj`',
          ],
        },
        atomMap: [0],
        smiles: 'CCCCCC',
        mf: 'C6H14',
        idCode: 'gGP@DiVj`@',
        mfInfo: {
          mass: 86.17558593719237,
          monoisotopicMass: 86.10955045122,
          charge: 0,
          mf: 'C6H14',
          atoms: { C: 6, H: 14 },
          unsaturation: 0,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'daD@@DjUZzjjhB`NDB`b`}PQFIfXV_hb@xUTNET',
            'dmt@@DjUUZzjjjlBbjNHCa@hHhOBDQbYfEePv]GzH`NEUCaU@',
            'foA@@@DjUUUZgMVjjjjjb@hiQpaQ@ND@hHTGm@bFHsFDrdLsdBrVJc}DHApjhNET',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'deT@@DjVVhZjjk@hR`b@xPJBJCuADXdYaQ~bHCaUPxUP',
            'dg|H@@rJIJIKPurzuUUUTQTUQqDdApaTCTGiSBbh[NbXWMp|\x7FQDIpjf\\Jh',
            'f`qA@@@YEDeDdeJj\\TYjjjjjbDhiQpbQ@NDDhFTGcHsFDbdLsdBrTJpvVqv_haBNETqpj`',
          ],
        },
        atomMap: [5],
        smiles: 'CCC1(C(CC)CC(=O)CC1)',
        mf: 'C10H17O',
        idCode: 'dcLH`MAYRUfUqfjjjX@@',
        mfInfo: {
          mass: 153.24175671061897,
          monoisotopicMass: 153.12794016748,
          charge: 0,
          mf: 'C10H17O',
          atoms: { C: 10, H: 17, O: 1 },
          unsaturation: 2.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'daD@@DiYbZjjdQY@xPJBJCqAdXdYGzH`NEUCaU@',
            'dcL@@DiYelfjjjjqJLHJ`NDB`b`|HYFIFPTUCYv_hb@xUTNET',
            'foA@@@DiYemtcIFjjjjjbHhpPRbe@ND@hHTGc@rFHcDDbdLsfBrVJsV_ha@NEUApj`',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'deT@@DjVVhZjjk@hR`b@xPJBJCuADXdYaQ~bHCaUPxUP',
            'dg|H@@rJIJIKPurzuUUUTQTUQqDdApaTCTGiSBbh[NbXWMp|\x7FQDIpjf\\Jh',
            'f`qA@@@YEDeDdeJj\\TYjjjjjbDhiQpbQ@NDDhFTGcHsFDbdLsdBrTJpvVqv_haBNETqpj`',
          ],
        },
        atomMap: [0],
        smiles: 'CCCCC(C)C',
        mf: 'C7H16',
        idCode: 'gNp@LdbJjj@@',
        mfInfo: {
          mass: 100.20220334203918,
          monoisotopicMass: 100.12520051568,
          charge: 0,
          mf: 'C7H16',
          atoms: { C: 7, H: 16 },
          unsaturation: 0,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'daD@@DiYbZjjdQY@xPJBJCqAdXdYGzH`NEUCaU@',
            'dcL@@DiYelfjjjjqJLHJ`NDB`b`|HYFIFPTUCYv_hb@xUTNET',
            'foA@@@DiYemtcIFjjjjjbHhpPRbe@ND@hHTGc@rFHcDDbdLsfBrVJsV_ha@NEUApj`',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'deT@@DjVVhZjjk@hR`b@xPJBJCuADXdYaQ~bHCaUPxUP',
            'dg|H@@rJIJIKPurzuUUUTQTUQqDdApaTCTGiSBbh[NbXWMp|\x7FQDIpjf\\Jh',
            'f`qA@@@YEDeDdeJj\\TYjjjjjbDhiQpbQ@NDDhFTGcHsFDbdLsdBrTJpvVqv_haBNETqpj`',
          ],
        },
        atomMap: [6],
        smiles: 'CC1(C(CC)CC(=O)CC1)',
        mf: 'C9H15O',
        idCode: 'dmtH`EAYRVYWxZjjf@@',
        mfInfo: {
          mass: 139.21513930577217,
          monoisotopicMass: 139.11229010302,
          charge: 0,
          mf: 'C9H15O',
          atoms: { C: 9, H: 15, O: 1 },
          unsaturation: 2.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'daD@@DiYbZjjdQY@xPJBJCqAdXdYGzH`NEUCaU@',
            'dcL@@DiYelfjjjjqJLHJ`NDB`b`|HYFIFPTUCYv_hb@xUTNET',
            'foA@@@DiYemtcIFjjjjjbHhpPRbe@ND@hHTGc@rFHcDDbdLsfBrVJsV_ha@NEUApj`',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjUZnjjjPJBHCa@hHhOTDQbYfEGzH`NEUCaU@',
            'dcL@@DjU[VnjjjjpJBHx`NDB`b`}HQFIfXTUcYtCgzH`NEUCaU@',
            'f`qA@@@YEDeDehTj\\UijjjjjbDHhQrbU@NDLhITGmHpdTaf\\bTJsVFrvNs}DHqpjiNET',
          ],
        },
        atomMap: [0],
        smiles: 'CCCCCC',
        mf: 'C6H14',
        idCode: 'gGP@DiVj`@',
        mfInfo: {
          mass: 86.17558593719237,
          monoisotopicMass: 86.10955045122,
          charge: 0,
          mf: 'C6H14',
          atoms: { C: 6, H: 14 },
          unsaturation: 0,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
            'daD@@DiYbZjjdQY@xPJBJCqAdXdYGzH`NEUCaU@',
            'dcL@@DiYelfjjjjqJLHJ`NDB`b`|HYFIFPTUCYv_hb@xUTNET',
            'foA@@@DiYemtcIFjjjjjbHhpPRbe@ND@hHTGc@rFHcDDbdLsfBrVJsV_ha@NEUApj`',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjUZnjjjPJBHCa@hHhOTDQbYfEGzH`NEUCaU@',
            'dcL@@DjU[VnjjjjpJBHx`NDB`b`}HQFIfXTUcYtCgzH`NEUCaU@',
            'f`qA@@@YEDeDehTj\\UijjjjjbDHhQrbU@NDLhITGmHpdTaf\\bTJsVFrvNs}DHqpjiNET',
          ],
        },
        atomMap: [6],
        smiles: 'CC1(C(CC)CC(=O)CC1C)',
        mf: 'C10H17O',
        idCode: 'dcLH`MAYrIQQQH}MUUTp@@',
        mfInfo: {
          mass: 153.24175671061897,
          monoisotopicMass: 153.12794016748,
          charge: 0,
          mf: 'C10H17O',
          atoms: { C: 10, H: 17, O: 1 },
          unsaturation: 2.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'deT@@DjVYjZjji@hR`NDB`b`}PQFIFPV_hb@xUTNET',
            'dk\\@@DjVY}j^VjjjjbBaJLhd`NDB`b`|hQFIFPVUcYvCdq~bHCaUPxUP',
            'foAA@@@YEDeDddcQbcMUUUUQBTTHYPj`GBFTDjCqdYcBQRFQsAYKEQkcY[OtPcGBjdxUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'deT@@DjVVhZjjk@hR`b@xPJBJCuADXdYaQ~bHCaUPxUP',
            'dg|H@@rJIJIKPurzuUUUTQTUQqDdApaTCTGiSBbh[NbXWMp|\x7FQDIpjf\\Jh',
            'f`qA@@@YEDeDdeJj\\TYjjjjjbDhiQpbQ@NDDhFTGcHsFDbdLsdBrTJpvVqv_haBNETqpj`',
          ],
        },
        atomMap: [0],
        smiles: 'CCCCC(CC)C',
        mf: 'C8H18',
        idCode: 'dax@@DjWzjh@@',
        mfInfo: {
          mass: 114.22882074688597,
          monoisotopicMass: 114.14085058014,
          charge: 0,
          mf: 'C8H18',
          atoms: { C: 8, H: 18 },
          unsaturation: 0,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'deT@@DjVYjZjji@hR`NDB`b`}PQFIFPV_hb@xUTNET',
            'dk\\@@DjVY}j^VjjjjbBaJLhd`NDB`b`|hQFIFPVUcYvCdq~bHCaUPxUP',
            'foAA@@@YEDeDddcQbcMUUUUQBTTHYPj`GBFTDjCqdYcBQRFQsAYKEQkcY[OtPcGBjdxUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'deT@@DjVVhZjjk@hR`b@xPJBJCuADXdYaQ~bHCaUPxUP',
            'dg|H@@rJIJIKPurzuUUUTQTUQqDdApaTCTGiSBbh[NbXWMp|\x7FQDIpjf\\Jh',
            'f`qA@@@YEDeDdeJj\\TYjjjjjbDhiQpbQ@NDDhFTGcHsFDbdLsdBrTJpvVqv_haBNETqpj`',
          ],
        },
        atomMap: [7],
        smiles: 'C1(C(CC)CC(=O)CC1)',
        mf: 'C8H13O',
        idCode: 'deTH`IAYRYe]njji`@',
        mfInfo: {
          mass: 125.18852190092537,
          monoisotopicMass: 125.09664003856,
          charge: 0,
          mf: 'C8H13O',
          atoms: { C: 8, H: 13, O: 1 },
          unsaturation: 2.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'deT@@DjVYjZjji@hR`NDB`b`}PQFIFPV_hb@xUTNET',
            'dk\\@@DjVY}j^VjjjjbBaJLhd`NDB`b`|hQFIFPVUcYvCdq~bHCaUPxUP',
            'foAA@@@YEDeDddcQbcMUUUUQBTTHYPj`GBFTDjCqdYcBQRFQsAYKEQkcY[OtPcGBjdxUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjUZnjjjPJBHCa@hHhOTDQbYfEGzH`NEUCaU@',
            'dcL@@DjU[VnjjjjpJBHx`NDB`b`}HQFIfXTUcYtCgzH`NEUCaU@',
            'f`qA@@@YEDeDehTj\\UijjjjjbDHhQrbU@NDLhITGmHpdTaf\\bTJsVFrvNs}DHqpjiNET',
          ],
        },
        atomMap: [0],
        smiles: 'CCCCCCC',
        mf: 'C7H16',
        idCode: 'gNp@DiUjj@@',
        mfInfo: {
          mass: 100.20220334203918,
          monoisotopicMass: 100.12520051568,
          charge: 0,
          mf: 'C7H16',
          atoms: { C: 7, H: 16 },
          unsaturation: 0,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'deT@@DjVYjZjji@hR`NDB`b`}PQFIFPV_hb@xUTNET',
            'dk\\@@DjVY}j^VjjjjbBaJLhd`NDB`b`|hQFIFPVUcYvCdq~bHCaUPxUP',
            'foAA@@@YEDeDddcQbcMUUUUQBTTHYPj`GBFTDjCqdYcBQRFQsAYKEQkcY[OtPcGBjdxUP',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
            'did@@DjUZnjjjPJBHCa@hHhOTDQbYfEGzH`NEUCaU@',
            'dcL@@DjU[VnjjjjpJBHx`NDB`b`}HQFIfXTUcYtCgzH`NEUCaU@',
            'f`qA@@@YEDeDehTj\\UijjjjjbDHhQrbU@NDLhITGmHpdTaf\\bTJsVFrvNs}DHqpjiNET',
          ],
        },
        atomMap: [7],
        smiles: 'C1(C(CC)CC(=O)CC1C)',
        mf: 'C9H15O',
        idCode: 'dmtH`EAYrJJJIEajjjX@@',
        mfInfo: {
          mass: 139.21513930577217,
          monoisotopicMass: 139.11229010302,
          charge: 0,
          mf: 'C9H15O',
          atoms: { C: 9, H: 15, O: 1 },
          unsaturation: 2.5,
        },
        fragmentType: 'cyclic',
      },
    ]);
  });
  it('C1CCC1', () => {
    const molecule = Molecule.fromSmiles('C1CCC1'); // just cycle
    const result = fragment(molecule);
    expect(result).toStrictEqual([
      {
        mf: 'C4H8',
        idCode: 'gBP@DiVj`@',
        mfInfo: {
          mass: 56.10646961938721,
          monoisotopicMass: 56.06260025784,
          charge: 0,
          mf: 'C4H8',
          atoms: { C: 4, H: 8 },
          unsaturation: 1,
        },
        fragmentType: 'Molecular Ion',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gBP@DiVj`NDJBTGdLf_hdCaUQpj`',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gBP@DiVj`NDJBTGdLf_hdCaUQpj`',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
          ],
        },
        atomMap: [0],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gBP@DiVj`NDJBTGdLf_hdCaUQpj`',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gBP@DiVj`NDJBTGdLf_hdCaUQpj`',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
          ],
        },
        atomMap: [1],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gBP@DiVj`NDJBTGdLf_hdCaUQpj`',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gBP@DiVj`NDJBTGdLf_hdCaUQpj`',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
          ],
        },
        atomMap: [0],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
      {
        hose: {
          bond1: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gBP@DiVj`NDJBTGdLf_hdCaUQpj`',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
          ],
          bond2: [
            'eF@Hp\\IPUA~b`xUTxUP',
            'gBP@DiVj`NDJBTGdLf_hdCaUQpj`',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
            'gBP@DiVj`FDJBTGzI@xUT\\Jh',
          ],
        },
        atomMap: [2],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'cyclic',
      },
    ]);
  });
  it('CCCCCC(CC)CCC', () => {
    const molecule = Molecule.fromSmiles('CCCCCC(CC)CCC'); // just cycle
    const result = fragment(molecule);
    expect(result).toStrictEqual([
      {
        mf: 'C11H24',
        idCode: 'dmT@@DjUWzjjh@@',
        mfInfo: {
          mass: 156.3086729614264,
          monoisotopicMass: 156.18780077352,
          charge: 0,
          mf: 'C11H24',
          atoms: { C: 11, H: 24 },
          unsaturation: 0,
        },
        fragmentType: 'Molecular Ion',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'eM@HzCaJBhOIewzJCaUSaU@',
          'gC`@Dkj@xPhIP^pr\\l\x7FQHGBjcaU@',
          'gJP@DkZhCaB`eAxcIrsY~bPNEUGBj@',
          'gGP@DkVj`NDJBTGjLgKMas}D`\\JjNET',
        ],
        atomMap: [0],
        smiles: 'C',
        mf: 'CH3',
        idCode: 'eFBAYc@@',
        mfInfo: {
          mass: 15.03455815890258,
          monoisotopicMass: 15.02347509669,
          charge: 0,
          mf: 'CH3',
          atoms: { C: 1, H: 3 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'eM@HzCaJBhOIewzJCaUSaU@',
          'gC`@Dkj@xPhIP^pr\\l\x7FQHGBjcaU@',
          'gJP@DkZhCaB`eAxcIrsY~bPNEUGBj@',
          'gGP@DkVj`NDJBTGjLgKMas}D`\\JjNET',
        ],
        atomMap: [1],
        smiles: 'CCCCC(CC)CCC',
        mf: 'C10H21',
        idCode: 'dmT@`@VTeUeZjjh@@',
        mfInfo: {
          mass: 141.2741148025238,
          monoisotopicMass: 141.16432567683,
          charge: 0,
          mf: 'C10H21',
          atoms: { C: 10, H: 21 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
          'gJP@DiZhCaB`eAxcIbs]~bPNEUGBj@',
          'gGP@Di^j`NDJBTGjLfKMqs}D`\\JjNET',
          'dax@@Di]jjh@xPJBJCsAdXfYqYT_hb@xUTNET',
        ],
        atomMap: [0],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
          'gJP@DiZhCaB`eAxcIbs]~bPNEUGBj@',
          'gGP@Di^j`NDJBTGjLfKMqs}D`\\JjNET',
          'dax@@Di]jjh@xPJBJCsAdXfYqYT_hb@xUTNET',
        ],
        atomMap: [2],
        smiles: 'CCCC(CC)CCC',
        mf: 'C9H19',
        idCode: 'ded@`@VTeVUjjj@@',
        mfInfo: {
          mass: 127.247497397677,
          monoisotopicMass: 127.14867561237,
          charge: 0,
          mf: 'C9H19',
          atoms: { C: 9, H: 19 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
          'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh',
          'dax@@DiUjjh@xPJBJCsAdXfYaQW_hb@xUTNET',
          'ded@@DiUmjjj@NDB`b`|HYFIfXTUsYv_hb@xUTNET',
        ],
        atomMap: [0],
        smiles: 'CCC',
        mf: 'C3H7',
        idCode: 'gC`H@liKT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
          'gGP@DiVj`NDJBTGbLfKMgzI@xUT\\Jh',
          'dax@@DiUjjh@xPJBJCsAdXfYaQW_hb@xUTNET',
          'ded@@DiUmjjj@NDB`b`|HYFIfXTUsYv_hb@xUTNET',
        ],
        atomMap: [3],
        smiles: 'CCC(CC)CCC',
        mf: 'C8H17',
        idCode: 'diD@`@VTeYVjj`@',
        mfInfo: {
          mass: 113.22087999283019,
          monoisotopicMass: 113.13302554791,
          charge: 0,
          mf: 'C8H17',
          atoms: { C: 8, H: 17 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
          'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`',
          'ded@@DiYUjjj@NDB`b`}pYFIFXVUcY~bHCaUPxUP',
          'dmT@@DiYUZjjjDhCa@hHhOJFQbQfEeXv]`}O_hb@xUTNET',
        ],
        atomMap: [0],
        smiles: 'CCCC',
        mf: 'C4H9',
        idCode: 'gJPH@liJuP@',
        mfInfo: {
          mass: 57.114410373442986,
          monoisotopicMass: 57.07042529007,
          charge: 0,
          mf: 'C4H9',
          atoms: { C: 4, H: 9 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
          'gNp@DiYjj@xPhIP^HrXhv_hdCaUQpj`',
          'ded@@DiYUjjj@NDB`b`}pYFIFXVUcY~bHCaUPxUP',
          'dmT@@DiYUZjjjDhCa@hHhOJFQbQfEeXv]`}O_hb@xUTNET',
        ],
        atomMap: [4],
        smiles: 'CC(CC)CCC',
        mf: 'C7H15',
        idCode: 'dax@`@VTeeZjh@@',
        mfInfo: {
          mass: 99.1942625879834,
          monoisotopicMass: 99.11737548345,
          charge: 0,
          mf: 'C7H15',
          atoms: { C: 7, H: 15 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
          'dax@@DjUZjh@xPJBJCuADXfYaY~bHCaUPxUP',
          'ded@@DjUWjjj`J@xPJBJCpaDXfYaYVMwY~bHCaUPxUP',
          'dmT@@DjUWzjjj@hCa@hHhOJDQbYfEeXw]`}N_hb@xUTNET',
        ],
        atomMap: [0],
        smiles: 'CCCCC',
        mf: 'C5H11',
        idCode: 'gGPH@liJmU@@',
        mfInfo: {
          mass: 71.1410277782898,
          monoisotopicMass: 71.08607535453,
          charge: 0,
          mf: 'C5H11',
          atoms: { C: 5, H: 11 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
          'dax@@DjUZjh@xPJBJCuADXfYaY~bHCaUPxUP',
          'ded@@DjUWjjj`J@xPJBJCpaDXfYaYVMwY~bHCaUPxUP',
          'dmT@@DjUWzjjj@hCa@hHhOJDQbYfEeXw]`}N_hb@xUTNET',
        ],
        atomMap: [5],
        smiles: 'C(CC)CCC',
        mf: 'C6H13',
        idCode: 'gNpH@liLkUT@@',
        mfInfo: {
          mass: 85.16764518313659,
          monoisotopicMass: 85.10172541899,
          charge: 0,
          mf: 'C6H13',
          atoms: { C: 6, H: 13 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
          'gNp@DjUjj@xPhIP^hbXlvGotRApjhxUP',
          'diD@@DjUvjj`Ca@hHhO\\DQbYfEuXv_hb@xUTNET',
          'ded@@DjUujjj`J@xPJBJCtaDXfYa]VMgXO_hb@xUTNET',
        ],
        atomMap: [0],
        smiles: 'CCCCCCCCC',
        mf: 'C9H19',
        idCode: 'ded@`@VTeUUjjj@@',
        mfInfo: {
          mass: 127.247497397677,
          monoisotopicMass: 127.14867561237,
          charge: 0,
          mf: 'C9H19',
          atoms: { C: 9, H: 19 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
          'gNp@DjUjj@xPhIP^hbXlvGotRApjhxUP',
          'diD@@DjUvjj`Ca@hHhO\\DQbYfEuXv_hb@xUTNET',
          'ded@@DjUujjj`J@xPJBJCtaDXfYa]VMgXO_hb@xUTNET',
        ],
        atomMap: [6],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'eM@HzCaJBhOIewzJCaUSaU@',
          'gJP@DkjhCaB`eA{CIrc}D`\\JjNET',
          'gNp@Dkejj@xPhIP^hr\\hvGOtRApjhxUP',
          'diD@@DkeVjj`Ca@hHhO\\FQrQfEeXv_hb@xUTNET',
        ],
        atomMap: [0],
        smiles: 'CCCCCC(C)CCC',
        mf: 'C10H21',
        idCode: 'dmT@`@VTeUYzjjh@@',
        mfInfo: {
          mass: 141.2741148025238,
          monoisotopicMass: 141.16432567683,
          charge: 0,
          mf: 'C10H21',
          atoms: { C: 10, H: 21 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'eM@HzCaJBhOIewzJCaUSaU@',
          'gJP@DkjhCaB`eA{CIrc}D`\\JjNET',
          'gNp@Dkejj@xPhIP^hr\\hvGOtRApjhxUP',
          'diD@@DkeVjj`Ca@hHhO\\FQrQfEeXv_hb@xUTNET',
        ],
        atomMap: [7],
        smiles: 'C',
        mf: 'CH3',
        idCode: 'eFBAYc@@',
        mfInfo: {
          mass: 15.03455815890258,
          monoisotopicMass: 15.02347509669,
          charge: 0,
          mf: 'CH3',
          atoms: { C: 1, H: 3 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
          'dax@@DjUZjh@xPJBJCuADXfYaY~bHCaUPxUP',
          'diD@@DjUVjjhB`NDB`b`|HQFIfXVUc]w_hb@xUTNET',
          'ded@@LdbRRMUUTAPGBAPQP^dHcDsLKJqn{as}DPGBjapj`',
        ],
        atomMap: [0],
        smiles: 'CCCCCCCC',
        mf: 'C8H17',
        idCode: 'diD@`@VTeUVjj`@',
        mfInfo: {
          mass: 113.22087999283019,
          monoisotopicMass: 113.13302554791,
          charge: 0,
          mf: 'C8H17',
          atoms: { C: 8, H: 17 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'gJP@DjZhCaB`eAyBIgzI@xUT\\Jh',
          'dax@@DjUZjh@xPJBJCuADXfYaY~bHCaUPxUP',
          'diD@@DjUVjjhB`NDB`b`|HQFIfXVUc]w_hb@xUTNET',
          'ded@@LdbRRMUUTAPGBAPQP^dHcDsLKJqn{as}DPGBjapj`',
        ],
        atomMap: [8],
        smiles: 'CCC',
        mf: 'C3H7',
        idCode: 'gC`H@liKT@@',
        mfInfo: {
          mass: 43.08779296859618,
          monoisotopicMass: 43.05477522561,
          charge: 0,
          mf: 'C3H7',
          atoms: { C: 3, H: 7 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
          'gGP@DiZj`NDJBTGbLfJMwzI@xUT\\Jh',
          'dax@@Di[Zjh@xPJBJCsAdXdYqYV_hb@xUTNET',
          'diD@@Di[VjjhR`NDB`b`|HYFIF\\VUcYw_hb@xUTNET',
        ],
        atomMap: [0],
        smiles: 'CCCCCC(CC)C',
        mf: 'C9H19',
        idCode: 'ded@`@VTeUYjjj@@',
        mfInfo: {
          mass: 127.247497397677,
          monoisotopicMass: 127.14867561237,
          charge: 0,
          mf: 'C9H19',
          atoms: { C: 9, H: 19 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'gC`@Dij@xPhIP^PrY~bPNEUGBj@',
          'gGP@DiZj`NDJBTGbLfJMwzI@xUT\\Jh',
          'dax@@Di[Zjh@xPJBJCsAdXdYqYV_hb@xUTNET',
          'diD@@Di[VjjhR`NDB`b`|HYFIF\\VUcYw_hb@xUTNET',
        ],
        atomMap: [9],
        smiles: 'CC',
        mf: 'C2H5',
        idCode: 'eMBAYRZ@',
        mfInfo: {
          mass: 29.061175563749384,
          monoisotopicMass: 29.03912516115,
          charge: 0,
          mf: 'C2H5',
          atoms: { C: 2, H: 5 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'eM@HzCaJBhOIewzJCaUSaU@',
          'gC`@Dkj@xPhIP^pr\\l\x7FQHGBjcaU@',
          'gGP@DkZj`NDJBTGbLgKMGzI@xUT\\Jh',
          'dax@@DkYZjh@xPJBJCsAd\\fYAYV_hb@xUTNET',
        ],
        atomMap: [0],
        smiles: 'CCCCCC(CC)CC',
        mf: 'C10H21',
        idCode: 'dmT@`@VTeUYZjjh@@',
        mfInfo: {
          mass: 141.2741148025238,
          monoisotopicMass: 141.16432567683,
          charge: 0,
          mf: 'C10H21',
          atoms: { C: 10, H: 21 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
      {
        hose: [
          'eF@Hp\\IPUA~b`xUTxUP',
          'eM@HzCaJBhOIewzJCaUSaU@',
          'gC`@Dkj@xPhIP^pr\\l\x7FQHGBjcaU@',
          'gGP@DkZj`NDJBTGbLgKMGzI@xUT\\Jh',
          'dax@@DkYZjh@xPJBJCsAd\\fYAYV_hb@xUTNET',
        ],
        atomMap: [10],
        smiles: 'C',
        mf: 'CH3',
        idCode: 'eFBAYc@@',
        mfInfo: {
          mass: 15.03455815890258,
          monoisotopicMass: 15.02347509669,
          charge: 0,
          mf: 'CH3',
          atoms: { C: 1, H: 3 },
          unsaturation: 0.5,
        },
        fragmentType: 'acyclic',
      },
    ]);
  });
  it('noMolecule', () => {
    const molecule = Molecule.fromSmiles('');
    const result = fragment(molecule);
    expect(result).toStrictEqual([
      {
        mf: '',
        idCode: 'd@',
        mfInfo: {
          mass: 0,
          monoisotopicMass: 0,
          charge: 0,
          mf: '',
          atoms: {},
          unsaturation: 1,
        },
        fragmentType: 'Molecular Ion',
      },
    ]);
  });
});
